### ISSUE TITLE
[header line height] Allow different heights for column group lines in header

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#1115] opened 2016-08-31 16:36 UTC
We need to reduce the group header height (just increased by setting headerHeight value for multi rows header text) by doing this column header height increased but group header height also increased along it. Is there any way to change the different color of group header and column header like showing in second snapshot? How we get rid of all grid lines except black vertical line as a group headers separator with column header bottom text-align? Same like in second attached snapshot. How we can achieve same look and feel?

Currently we have this
[https://1drv.ms/i/s!AnrJsIrWjGXuxGu2cOqdGsDKuG3X]
We want like this
[https://1drv.ms/i/s!AnrJsIrWjGXuxGr_kg0fPdcKbLLj]

Any help would be appreciated.

**Comment by ceolter** [comment] 2016-09-02 12:56
no way to do it. have it added to list. no promise on when it gets implemented.

what you can do is change the style (colors, borders etc), but not the height.

**Comment by rvberloo** [comment] 2017-01-05 09:54
Same question for me, increased height to have spave for rotated labels but group headers should stay default height

**Comment by seanlandsman** [comment] 2017-01-24 10:45
tracked by AG-137
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-25 09:11
duplicate of https://github.com/ceolter/ag-grid/issues/680

**Closed by ceolter** 2017-01-25 09:11 UTC
Labels: enhancement
