### ISSUE TITLE
Touch devices / mobile devices support: Column Resizing and Moving

### ISSUE THREAD

**Issue by Ruud-cb** [ceolter/ag-grid#1053] opened 2016-08-03 08:26 UTC
I'm not sure if this has worked in the past, but it would be highly appreciated if these functionalities work on smaller devices. Actually, the whole reason behind moving, resizing and pinning columns is due having a smaller screen and have the ability to put the most important information on the left side, with a smaller width.

I can imagine that moving (drag & drop) is quite difficult on touch devices, I could solve that by using a context menu (same for pinning is done) to move a column to the left or right. But resizing is a bit more hacky to do it via a context menu or another popup to change the width.  

Since ag-grid is a bit similar to angular UI grid (in terms of architecture), it might be a good idea to see how they have done it.

**Comment by Ruud-cb** [comment] 2016-08-05 12:45
This might be helpful:
https://github.com/angular-ui/ui-grid/blob/master/src/features/resize-columns/js/ui-grid-column-resizer.js#L463
I guess modifying this file by adding event listeners would be enough?
https://github.com/ceolter/ag-grid/blob/master/src/ts/headerRendering/horizontalDragService.ts#L54

**Comment by ceolter** [comment] 2016-08-16 10:13
thank you for raising. getting ag-Grid to work on touch is definatly something we want to do. in approx 2 years from now, i feel that this will be expected as standard for grids in web UI.

```Since ag-grid is a bit similar to angular UI grid``` - that made me smile!!! for the record, i used ui-grid years ago, but never looked into it's source code. i copied the concept of gridOptions and columnDefinitions, but after that, any similarities are coincidental. ui-grid is based on angular 1, ag-Grid is based on it's own custom internal framework.

that's for the pointers, i'll come back to this when we dedicate a release to improving out touch experience.

**Comment by Ruud-cb** [comment] 2016-08-16 10:35
Haha, that's the whole point for me for switching to ag-grid as well, I've read [your blog ](https://www.ag-grid.com/why-the-world-needed-another-angularjs-grid/) :).
2 years from now seems a bit long though :(. Most features work just fine on mobile, yet the core features  (like resizing and moving) are especially needed for small devices.
Anyway, thanks for the heads up, I'll have to do some workaround for this...

**Comment by ceolter** [comment] 2016-08-16 15:06
i didn't mean i'd do it in two years. i mean in two years it will be expected in all grids!!! hopefully will get to it later this year or early next year.

**Comment by Ruud-cb** [comment] 2016-08-16 15:29
Ah misunderstanding. Looking forward to this :+1:

**Comment by Ruud-cb** [comment] 2016-09-29 08:41
Hi @ceolter, The requirement to have the columns resized has come up a bit higher now. I'm wondering how difficult it would be to implement this? Do you think my second comment is appropriate or is it far more difficult? Considering forking it. Else I would have to create some overlay to resize a column which isn't user-friendly.

**Comment by ceolter** [comment] 2016-10-11 13:52
@Ruud-cb pity it's resizing has come up tops, and not moving. we are releasing today, and moving cols will be possible via dragging. but resizing will not.

i don't think resizing is easy via touch - i'm not fond of having to drag the edge of the column, especially if we are allowing moving of columns via drag - as it would be intuitive to drag the centre to move, and drag the edge to resize.

given the next release will allow easy column menu access, how about you put options into the menu to resize? (you can currently choose the autosize option)

ps closing this as moving columns and general 'touch' support is now in. please open another for 'resize' if you the menu option isn't going to work. however it won't get done in the next few weeks as i'm about to get married and go on honeymoon.

**Closed by ceolter** 2016-10-11 13:52 UTC

**Comment by Ruud-cb** [comment] 2016-10-11 15:10
Hey @ceolter That's awesome! Will be testing that tomorrow 👍 .
I've seen it working on angular ui grid, but they don't have the drag feature for touch devices. So Technically it should be possible but I can understand if it's difficult. The auto resize has to be used now or do that automatically per column.
Enjoy your honeymoon, congrats!

**Comment by Ben-CA** [comment] 2023-01-31 15:45
Seems to be an issue with column resizing on touch devices with AG Grid v. 29 - worked on v. 27.

**Comment by StephenCooper** [comment] 2023-01-31 16:09
@Ben-CA can you please open a new issue for this please with details on how we can reproduce it? Specifically please include details about the touch device used, is it a real device and not just emulated?

**Comment by Ben-CA** [comment] 2023-01-31 16:13
@StephenCooper  - I created a ticket in Enterprise support (#25799) a short time ago with details (both real devices and emulators); came across this issue by searching for a workaround and figured I'd post a note in case anyone else was having the same issues. (Do you want an issue posted in GitHub as well?)

**Comment by StephenCooper** [comment] 2023-01-31 16:19
No need to post to Github as well. Enterprise support is the best place for you to report this in terms of guaranteed response and help.

**Comment by Ben-CA** [comment] 2023-02-03 16:04
I've heard back from Enterprise support, they have this issue in their pipeline and expect it to be resolved in the next release in 6-8 weeks.

AG-7955 [Regression] Cannot resize columns on touch devices

If anyone comes up with a workaround for 29.0.0 in the mean time, please post it.
