### ISSUE TITLE
Have way for filter to 'reset' if values in grid have changed

### ISSUE THREAD

**Issue by AkosLukacs** [ceolter/ag-grid#739] opened 2016-02-25 10:55 UTC
Here is the example:
http://plnkr.co/edit/FCQJwiaMenKYKOXQlZIo?p=preview

If you just press the 'change to Toyota!' button, all rows will change to 'Toyota'.

If you first set a filter to only show Toyotas (only 1 row shown), and press the button, still only one row is visible instead of all rows...

If you change other filters manually, or call `gridApi.onFilterChanged()`, all three rows are shown as expected.
(Tested @ v.3.3.3, in Vivaldi, Chrome Canary, and Firefox, same behavior)

**Comment by ceolter** [comment] 2016-02-26 08:33
not sure what you are getting at.

i am aware of one problem, that the list inside the filter is created when the filter is first opened. so if you open filter, then close it (without doing any filtering), then click your button, then open filter again, the filter shows all the old values rather than just the toyota.

is this you point?

**Comment by AkosLukacs** [comment] 2016-02-26 09:16
Tried to capture it (below is an anim gif, i guess not included in emails), the steps:
- Everything is shown
- User filters rows (just as an example filter to toyota), only 1 row is shown
- Something happens, and more rows should be visible. In my real case, its SignalR pushing notification about row changed to the client, but just a button click in the example.
- side note: Not shown in the example, visible row contents are updated as expected √
- But if a row with the changed value should be visible after the changes, those rows are not shown until "something" happens. This can be the user changing filters, or calling `gridApi.onFilterChanged()` from code

![croppercapture 7](https://cloud.githubusercontent.com/assets/844331/13347983/25ccea84-dc71-11e5-8c6f-7d034a778ffd.Gif)

**Comment by ceolter** [comment] 2016-02-28 19:16
are you saying you change the row data and you are expecting the grid to pick up on this and filter the data again automatically?

**Comment by AkosLukacs** [comment] 2016-02-28 19:22
Yes. (Not "automagically" since I did call refreshRows.)
2016.02.28. 20:16 ezt írta ("Niall Crosby" <notifications@github.com>):

**Comment by simodo79** [comment] 2016-02-29 12:55
Hi,
we have the same problem in our web application.
You change a value in a cell and the filter list does not get updated before the next time that something causes the grid to bind to the values again. Not even calling onFilterChanged() works, otherwise it could have been used as a temporary workaround.

**Comment by shenco** [comment] 2016-03-21 21:25
Yes same issue here
e.g
https://www.ag-grid.com/angular-grid-filtering/exampleFilterModel.html

step 1 - filter on country just pick "Bahrain", now only 1 row is showing

step 2 - click on the Sport column filter, it still shows all the data, expected to see only "Athletics"

Thanks

**Comment by jbrauchler** [comment] 2016-08-16 14:22
Has anyone figured out a way to fix this?

**Comment by ceolter** [comment] 2016-08-16 15:29
two items above.

resetting filter if values have changed - there is now ```api.destroyFilter()``` to destroy a particular filter. you will need to set the values in it again if you wish to keep state.

values not getting filtered out, eg Bahrain above - this was a bug i have just fixed, happens when ```filterParams``` is left out. to get around, include a blank filterParams.

**Closed by ceolter** 2016-08-16 15:29 UTC

**Comment by jbrauchler** [comment] 2016-08-16 15:50
@ceolter So if I use `api.destroyFilter()` to destroy a filter how would I set those values based on what is in table

**Comment by ceolter** [comment] 2016-08-16 16:09
after you destroy the filter, it will be created from scratch again next time it is used.

next time a filter is used is either:
1 - user clicks header to show the filter
2 - you set the filter model via the api (explained in docs)

when the filter is created from scratch again, it will extract all the unique values form the dataset.

**Comment by jbrauchler** [comment] 2016-08-16 16:24
based on the example in the docs this does not seem to be the correct functionality. based off of the plnkr above can you show me an example of this working properly just so I can make sure we are on the same page.

**Comment by ceolter** [comment] 2016-08-16 16:47
demonstrated here:
https://www.ag-grid.com/example.php

filter persons name column with 'sophie beck' which results in two rows.

then look at filters on columns:
country - works as expected, gets filtered
language - works as expected, gets filtered
game name - fails, all values are shown

so you can use country and language to observe expected behaviour.

once i release the fix, then all columns will work.

**Comment by jbrauchler** [comment] 2016-08-16 17:08
looking at the code, I'm never seeing the destroyFilter() ever being used

**Comment by shenco** [comment] 2016-08-16 21:35
The result looks good from the demo grid, I really like this grid, trying to convince my company to buy the enterprise version! keep up with the great work!  Thanks!

**Comment by ceolter** [comment] 2016-08-17 11:02
```looking at the code, I'm never seeing the destroyFilter() being used.```
the demo doesn't use destroyFilter(), just demo's the set filter removing entries from the list due to other filters.

for destroyFilter(), see the filter API example here:
https://www.ag-grid.com/javascript-grid-filtering/index.php

**Comment by kaustubh77** [comment] 2020-06-21 09:07
@ceolter I am using this.gridApi.setQuickFilter(evt) for filtering the grid in my project. I want the following functionality to happen - 
1. Once filter is applied user will click/select a row
2. we will get the row node of the clicked row
3. Clear the quick filter to get back the original unfiltered grid
4. Scroll to the row which had selected (point 2) in the original grid
