### ISSUE TITLE
Unexpected Behavior When Dragging Locked Pinned Column with `suppressMoveWhenColumnDragging`

### ISSUE THREAD

**Issue by LakshmiCel** [ceolter/ag-grid#9598] opened 2024-12-21 19:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
# Issue: Unexpected Behavior When Dragging Locked Pinned Column with `suppressMoveWhenColumnDragging`

## Current Behavior

When `suppressMoveWhenColumnDragging` is set to `true`, dragging a locked pinned column to the pinning region results in unexpected behavior. The draggable component overlay gets stuck and behaves unexpectedly, leading to a console error.

To be more specific, lets suppose we drag a column which is lockPinned and in GridOptions we have provided suppressMoveWhenColumnDragging ,the draggable component overlay kind of gets stuck and behaves unexpectedly, leading to error in console for Uncaught TypeError: Cannot read properties of undefined (reading 'getLeft') 

Here is the stack trace
```
ag-grid-community.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getLeft')
at ag-grid-community.min.js:1:543659
at d.getColumnMoveAndTargetInfo (ag-grid-community.min.js:1:543780)
at d.getNormalisedXPositionInfo (ag-grid-community.min.js:1:543154)
at d.handleColumnDragWhileSuppressingMovement (ag-grid-community.min.js:1:541027)
at d.onDragging (ag-grid-community.min.js:1:540116)
at d.onDragStop (ag-grid-community.min.js:1:540331)
at l.onDragStop (ag-grid-community.min.js:1:538623)
at c.onDragStop (ag-grid-community.min.js:1:654218)
at u.onUpCommon (ag-grid-community.min.js:1:664962)
at u.onMouseUp (ag-grid-community.min.js:1:664874)
```

Grid Options for further reference 

`
const gridOptions = {
  columnDefs: [
    {
      field: "athlete",
      suppressMovable: true,
      cellClass: "suppress-movable-col",
      pinned: "left",
    },
    { field: "age", lockPinned: true, cellClass: "locked-col" },
    { field: "country" },
    { field: "year" },
    { field: "total", lockPosition: "right", cellClass: "locked-col" },
  ],
  suppressMoveWhenColumnDragging: true,
  defaultColDef: {
    flex: 1,
    lockPinned: true, // Dont allow pinning for this example
  },
  suppressDragLeaveHidesColumns: true,
};`

Sample code pen Example: [ReproducibleLink](https://codepen.io/LakshmiCel/pen/QwLvBWE)
Code Sand Box example [ReproducibleLink](https://codesandbox.io/p/sandbox/column-suppress-lock-forked-75kxny?file=%2Fmain.js%3A13%2C14) 
Use any above provided links, the later is the fork from Ag Grid Column Suppress Lock Example

Steps to reproduce:
Drag the locked pinned column to left to the pinning region
Notice how the draggable component gets stuck and on rapid motion it gets duplicated

Here is the screenshot and video attached for reference 

![image](https://github.com/user-attachments/assets/a35d4d5c-8bba-4ddc-a45c-142fcd29573d)

https://github.com/user-attachments/assets/cb51716d-7458-4ae4-9c90-1f99f2693a5e

* **AG Grid version:** 33.0.0 [Community Edition]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by sabahang** [comment] 2024-12-23 17:54
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13770**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed as completed by sabahang** 2024-12-23 17:54 UTC
Labels: AG-13770
