### ISSUE TITLE
Bugged: Infinite scrolling + Pinned columns (simple fix)

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/ag-grid#395] opened 2015-08-25 22:30 UTC
If you use infinite scrolling and pinned columns together, you can scroll on the pinned columns with the mousewheel. The scroll destroys the view.

It looks to be caused because the element borderLayout_eGridPanel has overflow set to "auto". Removing that fixes the issue. I think this is probably a simple fix, but I'm not entirely sure why it's EVER set to auto, so I thought I'd send you the information and you could apply the simple fix in a way that wouldn't break other things.

Screenshots:

With overflow auto (default)
<img width="1343" alt="screen shot 2015-08-25 at 3 28 27 pm" src="https://cloud.githubusercontent.com/assets/1831484/9481318/ff4d41e8-4b3d-11e5-8826-0e6d7aefbf1d.png">

Without overflow auto
<img width="1300" alt="screen shot 2015-08-25 at 3 28 14 pm" src="https://cloud.githubusercontent.com/assets/1831484/9481322/0955bdd2-4b3e-11e5-9563-14e004da63a5.png">

**Comment by ceolter** [comment] 2015-08-26 11:35
@scotthovestadt i can't reproduce. how do you scroll over the pinned columns? scrolling while over the pinned columns i understood to be something you could not do.

**Comment by scotthovestadt** [comment] 2015-08-26 13:37
Infinite scrolling + Datasource + Mac trackpad scrolling

The fix is definitely not setting overflow auto on that specific element

**Comment by scotthovestadt** [comment] 2015-08-26 19:16
@ceolter My pull request for #398 fixes this bug! Thanks for your time in reviewing.

**Comment by ceolter** [comment] 2015-08-26 21:03
@scotthovestadt  will take a look soon. thanks for PR.

**Comment by scotthovestadt** [comment] 2015-08-26 22:59
@ceolter Thanks! It will help me a lot if you can merge it in and do a release soon! :+1: 

I've been using it locally with almost no issues. I made another small commit to handle the one issue I found.

**Comment by ceolter** [comment] 2017-01-17 16:11
this is now fixed i believe.

**Closed by ceolter** 2017-01-17 16:11 UTC
