### ISSUE TITLE
[grid height] Grid height based on rows

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid#1215] opened 2016-10-21 13:33 UTC
Copy from https://github.com/ceolter/ag-grid-ng2/issues/71 due to being in the wrong git repository.

As Niall mentions [here](https://www.ag-grid.com/forum/showthread.php?tid=4266&pid=10578#pid10578):

>  are you expecting the grid height to adjust with the number of rows? if yes, this is not a feature we support (if it worked in a previous version of ag-Grid, this was by accident).

This accident was in fact the case. The grid was capable of growing based on its row count and it was great. Several versions ago this stopped working and we didn't bother as we're still in some sort of prototype stage, but currently it would help a lot (for a single page application that uses only the browser scroll bar, e.g all components should be stretched to full height).

This is half possible alread by setting `forPrint` in `gridOptions`. Sadly due to the lack of vertical scrolling the grid crashes upon tabbing, as some elements are not available in this mode that the grid requires. I assume it's really only for printing.

Any chances this might be added again?

**Comment by seanlandsman** [comment] 2016-10-21 15:45
Thanks @stephanjust - we'll take a look at this as soon as possible

**Comment by tystol** [comment] 2016-10-22 00:06
+1 - would be very handy for us also

We currently use ag-grid for all of our data-focused tables (laying out in a fixed height div that we set to fill to the remaining available window space). But for our navigation/content related tables we prefer the whole page to scroll, and therefor don't use ag-grid. It would be very nice if we could standardize both of these use cases to ag-grid. Understand there are performance implications (you loose any benefit of virtual scrolling) but for navigation/content purposes the grid will never be that large anyway.

**Comment by ceolter** [comment] 2016-10-31 14:08
it's on our list, but low priority, so not scheduled work yet. it will get done, but can't give an eta.

**Comment by ceolter** [comment] 2017-01-24 13:06
tracked by AG-148
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-25 08:54
duplicate of https://github.com/ceolter/ag-grid/issues/1105
closing

**Closed by ceolter** 2017-01-25 08:54 UTC
Labels: enhancement
