### ISSUE TITLE
unable to find bean reference csvCreator while initialising

### ISSUE THREAD

**Issue by Steve-Holman** [ceolter/ag-grid#1778] opened 2017-07-24 16:31 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
agGrid is throwing exception errors when running IE:
ag-Grid: unable to find bean reference csvCreator while initialising GridApi
ag-Grid: unable to find bean reference csvCreator while initialising  Object
ag-Grid: unable to find bean reference csvCreator while initialising GridPanel
ag-Grid: unable to find bean reference csvCreator while initialising BeanStub
ag-Grid: unable to find bean reference csvCreator while initialising  Object
ag-Grid: unable to find bean reference csvCreator while initialising ClipboardService
ag-Grid: unable to find bean reference csvCreator while initialising  Object

Tested with Chrome (59.0.3071.115 64-bit) and not getting these errors.

**Expected behavior**
agGrid should not be throwing these errors. ;-)

**Minimal reproduction of the problem with instructions**
STEPS TO REPRODUCE:
Using IE 11 run in developer mode (F12) and navigate to 
https://www.ag-grid.com/javascript-grid-export/?framework=all#gsc.tab=0

You will see multiple errors in the console log

**What is the motivation / use case for changing the behavior?**
agGrid should not be throwing any errors. 

**Please tell us about your environment:**
Windows 7, IE 11 

* **ag-Grid version:** X.X.X
ag-Grid v12.0

* **Browser:**
"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; rv:11.0) like Gecko"

* **Language:** ES5

**Comment by makinggoodsoftware** [comment] 2017-07-26 07:46
This was fixed in our latest release 12.0.1

**Closed by makinggoodsoftware** 2017-07-26 07:46 UTC

**Comment by fastex** [comment] 2017-07-26 12:33
Bug was fixed in Chrome, but still reprodused for me in IE11.

**Comment by basvandenberg** [comment] 2017-08-02 08:09
I get the same error in Chrome/FireFox/IE11 while using `ag-grid` 12.0.1

I use `ag-grid` in an angular web application (`ag-grid-angular` 12.0.0), and use `angular-cli` for building. The error is only thrown for a production build (`ng build --prod`) but not for a development build (`ng build`).

**Comment by luis-aranda** [comment] 2019-07-12 18:53
im getting this one `ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub`

**Comment by atfzl** [comment] 2019-07-31 09:33
@luis-aranda I was getting the same issue, for me it was happening because i didn't clear the gridApi reference in my componentWillUnmount. So i was using gridApi even after `ag-grid` was unmounted.

**Comment by ievgenk** [comment] 2019-08-02 22:44
> @luis-aranda I was getting the same issue, for me it was happening because i didn't clear the gridApi reference in my componentWillUnmount. So i was using gridApi even after `ag-grid` was unmounted.

Can you please elaborate on that ? I am experiencing exactly the same issue! 
` ag-Grid: unable to find bean reference frameworkOverrides while initialising BeanStub`

@atfzl Do you mind showing how did you de-reference it in `componentWillUnmount`

**Comment by atfzl** [comment] 2019-08-03 05:19
This is what i did:

```js
class Table extends React.Component {
  onGridReady = (api) => {
    this.gridApi = api;
  }

  componentWillUnmount() {
    this.gridApi = undefined;
  }

  render() {
     return <AgGridReact        
                   onGridReady={event => {
                     this.onGridReady(event.api);
                   }}
                />;
  }
}
```

**Comment by ievgenk** [comment] 2019-08-06 18:07
Thank you that did not help me though. I am having same issues as @luis-aranda

**Comment by ankushjamdagani** [comment] 2019-09-02 10:26
I also got the same error as @luis-aranda followed by another error - 

`TypeError: Cannot read property 'addEventListenerOutsideAngular' of null`

Have you guys find any solutions?

**Comment by ievgenk** [comment] 2019-09-03 15:35
@ankushjamdagani 

Unfortunately no, I have been struggling with these error for a month or so. Very frustrating as we are enterprise clients and pay for this software :(

For us the error always gets triggered when we use setFilterModel() on columnApi.

But it seems that they fixed it here https://www.ag-grid.com/ag-grid-changelog/?fixVersion=21.2.0
AG-3246 but it still is happening.

@makinggoodsoftware Any ideas why ?

**Comment by TigerFranz88** [comment] 2019-09-23 10:26
@ievgenk 
I have the same issue, using the same ag-grid version.
My workaround was: 
```
if (!($event.api as any).gridCore.destroyed) {
              $event.columnApi.setColumnState([...]);
            }
```

**Comment by bseiryk** [comment] 2020-09-22 17:39
In my case, the root cause of this error was that I am trying to use the API of grid which has been unmounted.
And my solution was whenever grid is remounted again API object has to replaced.
`onGridReady(params) { this.gridApi = params.api; }`
