### ISSUE TITLE
[auto height] ui grid minRowsToShow equivalent? Setting grid height dynamically

### ISSUE THREAD

**Issue by dereklin** [ceolter/ag-grid#402] opened 2015-08-26 22:33 UTC
Hi, this is related to https://github.com/ceolter/angular-grid/issues/266

In ui grid, there is a minRowsToShow that can set the grid height dynamically.  Is there something similar in ag-grid?

**Comment by ceolter** [comment] 2015-08-27 08:43
nope, but good idea. will see what i can do.

**Comment by amalrajcharles** [comment] 2015-11-24 14:24
Are there any work around and temporary fix that can be made to show multiple lines ?

**Comment by ceolter** [comment] 2016-03-11 11:29
the work around is to figure it out yourself. the grid will fit the new height if you change it's height at runtime.

**Comment by darkguy2008** [comment] 2016-03-11 17:07
Well yeah, I could do a function to do that, do a sum of the heights of all the rows and update the div height accordingly, but you know, I was kinda expecting this to be an agGrid feature instead of reinventing the wheel

**Comment by ceolter** [comment] 2016-03-14 16:48
yes it will be in the grid at some point, the suggested workaround is just while your waiting for me to do it.

**Comment by ceolter** [comment] 2017-01-23 14:37
tracked by https://ag-grid.atlassian.net/browse/AG-61

**Comment by ceolter** [comment] 2017-01-24 17:55
this is a duplicate of this one: https://github.com/ceolter/ag-grid/issues/801

so closing

**Closed by ceolter** 2017-01-24 17:55 UTC
Labels: enhancement
