### ISSUE TITLE
Copy down is not utilizing processCellFromClipboard

### ISSUE THREAD

**Issue by mikevanilla** [ceolter/ag-grid#1539] opened 2017-03-21 14:32 UTC
[ X ] bug report 
[ ] feature request
[ ] support request

**Current behavior**
Currently the copySelectedRangeDown using the CTRL-D key is not processing data as it would for other clipboard events.

**Expected behavior**
Would expect the 'processCellForClipboard' to be called for top cell and 'processCellFromClipboard' to be called for the rest of selected range.

**Minimal reproduction of the problem with instructions**
Custom cell renderer for unique data object. CTRL-D for selected range and data is not processed by 'processCellForClipboard' or 'processCellFromClipboard'

**What is the motivation / use case for changing the behavior?**
Need to be able to prevent data corruption from this function. Would prefer it to properly process data or at least a way to override function / capture event.

**Please tell us about your environment:**
N/A

* **ag-Grid version:** X.X.X
8.2.x

* **Browser:**
Chrome / IE

* **Language:** [all]

**Comment by seanlandsman** [comment] 2017-03-22 09:38
Hi

We dont support the fill down keystroke you're describing. What you could do is listen for key events yourself and then manually trigger the clipboard operation, but as I say this is not somehting we support out of the box I'm afraid

**Comment by mikevanilla** [comment] 2017-03-22 10:24
Hi,
If it is not supported then why is it on by default with range selection? I am listening for key events and overriding your copy down but it is not a clean solution. I would prefer the built in method to work correctly or have the ability to disable it.
Thanks,-Mike
 
 
  On Wed, Mar 22, 2017 at 5:38 AM, seanlandsman<notifications@github.com> wrote:   
Hi

We dont support the fill down keystroke you're describing. What you could do is listen for key events yourself and then manually trigger the clipboard operation, but as I say this is not somehting we support out of the box I'm afraid

**Comment by seanlandsman** [comment] 2017-03-22 11:00
Turns out I was mistaken after looking further, apologies for this!

Your request seems reasonable based on this - I've raised issue AG-348 for this our side. We'll update this thread with updates as soon as we have any

thanks

**Comment by ceolter** [comment] 2017-06-09 11:41
done. will be in next release.

Callbacks processCellForClipboard() and processCellFromClipboard() now get invoked with doing Ctrl + D (copy range down)

**Closed by ceolter** 2017-06-09 11:41 UTC
Labels: bug

**Comment by makinggoodsoftware** [comment] 2017-06-27 06:27
Hi,

Just to let you know that as of 11.0.0 this has been implemented, see the changelog for more details..

https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0

**Comment by kasyap1986** [comment] 2019-02-20 11:34
**Current behavior**
Currently the copySelectedRangeDown using the CTRL-D key is not processing data as it would for other clipboard events.

**Expected behavior**
Would expect the 'processCellForClipboard' to be called for top cell and 'processCellFromClipboard' to be called for the rest of selected range.

**Minimal reproduction of the problem with instructions**
Custom cell renderer for unique data object. CTRL-D for selected range and data is not processed by 'processCellForClipboard' or 'processCellFromClipboard'

I am facing same issue. Ctrl+D should fill down, but deletes data from the grid. 
I am using " ag-grid-community@20.0.0:  version "20.0.0"" . Please help me for resolving the issue.
