### ISSUE TITLE
on paging controls, numbers appear as 1.00 (with 2 digit precision) prior to IE11

### ISSUE THREAD

**Issue by spfiedler** [ceolter/ag-grid#598] opened 2015-12-14 20:02 UTC
On IE9, 10, the paging controls display the page numbers with 2 digit precision rather than as integers, like this:

<<  <  1.00 of 1.00  >  >>

rather than 
<<  <  1 of 1  > >>

**Comment by ceolter** [comment] 2016-01-04 09:50
duplicate of https://github.com/ceolter/ag-grid/issues/159

**Closed by ceolter** 2016-01-04 09:50 UTC
