### ISSUE TITLE
Ag Grid React Cdn issue after Upgrade to 31.2.0 from 31.1.1

### ISSUE THREAD

**Issue by sachinchaubey** [ceolter/ag-grid#9564] opened 2024-12-16 18:17 UTC
- Hey what happen with your CDN links in 31.2.0?  ,I tried to upgrade React Ag Grid version from **31.1.1** to **31.2.0**, but it shows that the React Ag Grid is not found.
- And in your changelog of 31.2.0 version neither mentions any thing related to CDN changes.
- In Version 31.1.1 everything is working fine but in 31.2.0 give an error.
- What should I do please guide me.
- I will share you the code below -

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AG Grid React Example</title>
    <script src="https://unpkg.com/react@18.0.0/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18.0.0/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/ag-grid-community@31.2.0/dist/ag-grid-community.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ag-grid-react@31.2.0/bundles/ag-grid-react.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
    </style>
</head>
<body>
    <div id="saperate-page"></div>
    <script type="text/babel">
        const useState = React.useState;
        const useMemo = React.useMemo;
    
        const Scribble = () => {
            const [columns, setColumns] = useState([
                { headerName: "Color Name", field: "make" },
                { headerName: "Color (Sales Achievement in %)", field: "model" },
                { headerName: "Color Code", field: "price" },
            ]);
    
            const [rowData, setRowData] = useState([
                { make: 'Orange', model: "85%-90%", price: 34 },
                { make: 'Yellow', model: "90%-99.9%", price: 65 },
                { make: 'Green', model: "100%", price: 7654 },
            ]);
    
    
            const defaultColDef = useMemo(() => ({
                flex: 1,
            }), []);
    
    
            return (
                <div className="ag-theme-alpine" style={{ height: "calc(100vh - 170px)" }}>
                    <AgGridReact
                        columnDefs={columns}
                        rowData={rowData}
                        defaultColDef={defaultColDef}
                    />
                </div>
            );
        };
    
        ReactDOM.render(<Scribble />, document.querySelector("#saperate-page"));
    </script>
</body>
</html>
`
This code i working fine at version **31.1.1** or below but when I upgrade to **31.2.0** like given then AG Grid React does not find.
![Screenshot from 2024-12-16 23-41-12](https://github.com/user-attachments/assets/55cb3a64-71cf-4c64-88d3-776762f90eac)

**Comment by seanlandsman** [comment] 2024-12-17 07:14
Hi - this is a bug and will be fixed in a patch due out today or tomorrow (in version 33.0.3)

**Comment by sachinchaubey** [comment] 2024-12-17 16:01
@seanlandsman "Thank you! I hope it works smoothly and meets expectations."

**Comment by sachinchaubey** [comment] 2024-12-18 07:20
Hii

Why AG-12124 shifted to the backlog in your Ag grid pipeline but as you
mentioned before it will scheduled in 33.0.3 version

Thanks

**Comment by AG-Zoheil** [comment] 2024-12-18 13:33
Hi @sachinchaubey,

this was due to a label that was added to it. I can confirm it will be part of 33.0.3.

Thanks!

**Closed as completed by AG-Zoheil** 2024-12-18 13:33 UTC
