### ISSUE TITLE
How to load dynamic column and rows from http call (both column and record should be dynamic) in ag-grid

### ISSUE THREAD

**Issue by ajaiswal595** [ceolter/ag-grid#731] opened 2016-02-22 13:26 UTC
i have requirement like user will click on any table name then i have to render respective data in ag-grid.

i am using angular js 1.x.

i tried all the ways

                             $scope.gridOptions = {};
                       $scope.loadTableInGrid = function (tablename) {
      $http.post($scope.url + "/getPagingRecordImportedTable", { 'dbname': $stateParams.dbname, 'tableName': tablename, 'pageNumber': 1 }).success(
                                    function (response) {

                                        $scope.names = response.records;
                                        $scope.mdata = response.metadata;

                                        console.log(response.records);
                                        console.log(response.metadata);
                                        
                                      var  columnsize = 0;
                                        for (var obj in $scope.mdata) {
                                            if ($scope.mdata[obj]['columnsize'] > 20) {
                                                columnsize = 20;
                                            } else {
                                                columnsize = $scope.mdata[obj]['columnsize'];
                                            }
                                           
                                            $scope.columnDefs.push({
                                                "headerName": $scope.mdata[obj]['columnname'],
                                                "field": $scope.mdata[obj]['columnname']
                                            });
                                        }

                                       
                                        var gridDiv = document.querySelector('#myGrid');
                                        alert(gridDiv);
                                        new agGrid.Grid(gridDiv, $scope.gridOptions);
                                        $scope.gridOptions.api.setColumnDefs( $scope.columnDefs);
                                        $scope.gridOptions.api.setRowData(response.records);
                                        $scope.gridOptions.api.refreshView();

                                  
                                        console.log("-----------Data received");
                                    }).error(function (data) {
                                        alert(data);
                                    });
                            } else {
                                $scope.reset();
                                $scope.resetGridTableName();

                            }
                            console.log(tablename);
                        };

as per table name i have to load column and record both dynamically in grid .
but it is always saying "loading" and nothing to render.

if any example is there please refer or refactor my code.

**Comment by bwinchester** [comment] 2016-06-01 13:37
+1, I have the same flow, where dynamic data changes columns and data. Would suggest set ColumnDefs and setRowData return promises so people can depend on them reliably to be finished. Mean time, adding small timer to do refreshView() call. Also going to look at ng-if to remove ag-grid directive and redraw re-init it.

    scope.gridOptions.api.setColumnDefs(scope.tabData.columnDefs);
    scope.gridOptions.api.setRowData(scope.tabData.rowData);
    scope.gridOptions.api.refreshView();

**Comment by ceolter** [comment] 2016-06-01 13:57
you don't need promises, both setColumnDefs and setRowData will be complete when they return.

**Comment by bwinchester** [comment] 2016-06-01 14:29
In the above process @ceolter , The rows refresh with only the 1st 3 or 4 rows. Then when you scroll, the rows refresh again and all 1000 of them display.

**Comment by ceolter** [comment] 2016-06-06 16:59
then there is something else wrong, not to do with the original question in this thread.

can you try api.refreshView() after the data is set? maybe put it in a timeout (wait 0ms) to see if something does need to complete.

if you can reproduce in a plunker i can take a look? but with the above, not much i can suggest.

ps closing, as the reason for this thread to be opened inintially is gone off topic to what this is now. if you do find a specific problem, then a different issue specific to that problem would be better tnks.

**Closed by ceolter** 2016-06-06 16:59 UTC
