### ISSUE TITLE
[column] suppressMovable for column

### ISSUE THREAD

**Issue by dephiros** [ceolter/ag-grid#1046] opened 2016-07-29 22:19 UTC
I am attempting to have a column A not movable at index 0
- try setting suppressMovable but other column can still be dragged on column A
- the beforeColumnMoved event to stop user from moving columns if certain condition is met

**Comment by ua9msn** [comment] 2016-08-02 12:58
+1

**Comment by ceolter** [comment] 2016-08-15 14:41
fair point. i'm not sure beforeColumnMoved is the best way though. if it's always the first columns, then how about if first X columns are not movable, then you cannot put any other columns before them?

**Comment by dephiros** [comment] 2016-08-15 16:45
That sounds good to me. My end goal is to have n column at the beginning or end not movable

**Comment by light049** [comment] 2016-11-03 01:54
I would need this feature, too... 👍

**Comment by seanlandsman** [comment] 2017-01-24 10:42
tracked by AG-133
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-25 08:38
duplicate of https://github.com/ceolter/ag-grid/issues/853
closing

**Closed by ceolter** 2017-01-25 08:38 UTC
Labels: enhancement
