### ISSUE TITLE
AG Grid Vue3 Incorrect Documentation for Custom Cell Components

### ISSUE THREAD

**Issue by shopper360mst** [ceolter/ag-grid#9175] opened 2024-11-04 07:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
Links that has provided incorrect method of using custom cell components: 
https://codesandbox.io/p/sandbox/gy5crz?file=%2Fmain.js
https://www.ag-grid.com/vue-data-grid/component-cell-renderer/
The above links kept providing me the quoted component where i kept encountering this error instead : 
![image](https://github.com/user-attachments/assets/c7fe936c-cde3-4e34-a978-3001e6515ec6)

![image](https://github.com/user-attachments/assets/0e2efe6d-c631-44fb-805f-e68c9e5b1506)

![image](https://github.com/user-attachments/assets/09992f01-37a7-4dba-9b93-5ab853f16de7)

**Expected behavior**
What was correct and it worked for me was the only page at the beginning of the tutorial.
This has no quotation marks around the component name inside "cellRenderer".
![image](https://github.com/user-attachments/assets/441e2aa6-0a7d-4b46-9e6d-4551e5b5075c)

https://www.ag-grid.com/vue-data-grid/getting-started/#cell-components

**Please tell us about your environment:**
Windows 11, Vue-3

* **AG Grid version:** X.X.X
32.3.2

* **Browser:**
Microsoft Edge

* **Language:** 
ES6/7

**Comment by AG-Zoheil** [comment] 2024-12-12 14:13
Hi,

We are unable to reproduce the issue in the codesandbox you've reported and our examples work fine without any console warnings.

If the issue has already been resolved by other means, you can ignore this. If not, I'd advise upgrading to make sure you are using the latest versions of AG Grid.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-12-12 14:13 UTC
