### ISSUE TITLE
set initial filter

### ISSUE THREAD

**Issue by markus138** [ceolter/ag-grid#1081] opened 2016-08-16 08:29 UTC
Hello, I tried setting an initial filter on my list with `doesExternalFilterPass`& `gridOptions.api.onFilterChanged()`.  This does work, but after that I can't clear the filter since the list only has a filtered list available.

use case for example: show initially all items with status 'active', but allow the user to change to filter to any status.

I couldn't find anything on the docs, is this not supported?

**Comment by ceolter** [comment] 2016-08-16 15:05
yes it's supported.

i noticed the grid doesn't check 'isExternalFilterPresent' on startup. i've fixed this, will be in next release. however you have the workaround of calling onFilterChanged().

with regards the error, i cannot reproduce. i tested using the online example. i change it to start with 'above 50' and it worked fine. if you can provide a plunker, i can look, otherwise, can not reproduce :(

**Closed by ceolter** 2016-08-16 15:05 UTC
