### ISSUE TITLE
Do not truncate cell contents

### ISSUE THREAD

**Issue by lekhnath** [ceolter/ag-grid#645] opened 2016-01-16 09:17 UTC
How can I tell ag-grid not to truncate cell contents. I've a long paragraph to display in grid, but could not figure out how to display the whole content without truncating it.

In below figure as you can see 'Change to Process' column's cell content is truncated, I've shown the whole content in Inspection Panel.
![screenshot from 2016-01-16 14 54 18](https://cloud.githubusercontent.com/assets/4231691/12371638/7b9fcc7c-bc61-11e5-91eb-9ecb70e75fd7.png)

**Comment by ceolter** [comment] 2016-01-17 10:19
this is a duplicate of same on the forum. the forum is the preferred place to ask questions so closing this one. thanks..

**Closed by ceolter** 2016-01-17 10:19 UTC
