### ISSUE TITLE
Select and copy text from grid

### ISSUE THREAD

**Issue by joshikeerti** [ceolter/ag-grid#477] opened 2015-10-06 05:17 UTC
Are there any options to select and copy text from the grid? Currently I am not able to select and copy any text from the grid.

**Comment by ceolter** [comment] 2015-10-06 08:58
it's on my list, but not done yet. duplicate of this issue:
https://github.com/ceolter/ag-grid/issues/87

**Closed by ceolter** 2015-10-06 08:58 UTC
