### ISSUE TITLE
Newly introduced feature select all header checkbox doesn't work well with pagination. It should maintain the state of the header checkbox across different pages.

### ISSUE THREAD

**Issue by riteshwaghela** [ceolter/ag-grid#1481] opened 2017-02-20 10:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Select all header checkbox is not working well when the grid pagination is in place. If you select the header checkbox, it selects all the records on the first page which is perfectly fine. But when you go to the next page, the header checkbox shows still selected (it should not show it selected). And if you uncheck it and go to the first page, it shows it unselected and all rows are selected.
In short the state of the header checkbox is not maintained when pagination is in place.

**Expected behavior**
It should maintain the state of the header checkbox across different pages.

**Minimal reproduction of the problem with instructions**
Create a grid with pagination and header check box selection.
Make sure that the grid has at least 2-3 pages.
Now on the first page select the header check box. It will select all the rows.
Navigate to 2nd page, you will see the header check box still selected.
It should not be selected.

**What is the motivation / use case for changing the behavior?**
Select all header check box behavior should be consistent with all grid features such as pagination etc

**Please tell us about your environment:**
OS : Windows8
IDE : VSCode

* **ag-Grid version:** 8.0.1

* **Browser:**
"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by willhalling** [comment] 2017-02-20 16:20
Hi @riteshwaghela,

Thanks for raising this. I've raised this with core dev team and should be fixed in a future release. You can track progress on our pipeline (AG-255):

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by jathri** [comment] 2017-03-03 10:58
Header checbox does not reflect state of rows checkboxes even in normal, non-pagination mode. Even when there are none selected (checked) rows anymore (due to different type of actions), its state remains the same.
Steps:
- load array to grid (via gridOptions.api.setRowData)
- check a few rows
- load different array to grid (via gridOptions.api.setRowData)  withnout changing or reset column definitions -> checked rows are not anymore but header checkox keeps last state  
Will this please be fixed too?

**Comment by ceolter** [comment] 2017-03-03 13:20
fixed, will be in next release. and yes, both variations are fixed.

**Closed by ceolter** 2017-03-03 13:20 UTC
Labels: bug

**Comment by jathri** [comment] 2017-03-07 18:20
I would like to have one more question. Steps I mentioned above also leads to not firing onSelectionChanged. Which I need to update my selected rows counter. Will this fix please somehow fix this too?

**Comment by don-bluelinegrid** [comment] 2017-07-21 20:27
@ceolter 

Niall,

I had been waiting for the 'selectAll' feature being application virtual/pagination cases of the grid, so was pleased to see this resolved.

However, I'm trying to use this, with the ag-aurelia, and I can never see the column header checkbox appearing - it is always rendered with the `ag-hidden` CSS class applied.

Here is the colDef from my ag-aurelia template:

```
        <ag-grid-column if.bind="showColumn('selection')" col-id="checkbox-col" header-name='' 
            header-checkbox-selection.bind="true" header-checkbox-selection-filtered-only.bind="true"
            width.bind="30" min-width.bind="30" 
            checkbox-selection.bind="true"
            suppress-sorting.bind="true" suppress-filter.bind="true" suppress-resize.bind="true" 
            suppress-movable.bind="true" suppress-menu.bind="true" 
            pinned.bind="true" ></ag-grid-column>

```

Is there anything obvious here that would cause the header checkbox to not be set to visible?  It seems like I'm doing the equivalent of what's shown in the doc examples.

Thanks,
Don

**Comment by don-bluelinegrid** [comment] 2017-07-21 20:46
@ceolter 

I've also tried setting this config option in JavaScript, like so, but also seems to have no effect; the header checkbox is not visible:

```
  onGridReady(event, scope) {
    event.api.gridOptionsWrapper.gridOptions.onViewportChanged = function() {
      event.api && event.api.sizeColumnsToFit();
    };
    event.api.gridOptionsWrapper.gridOptions.onGridSizeChanged = function(){
      event.api && event.api.sizeColumnsToFit();
    };

    let selCol = event.api.columnController.getColumn('checkbox-col', event.api.columnController.gridColumns);
    let selColDef = selCol.colDef;
    selColDef.headerCheckboxSelection = true;
    selColDef.headerCheckboxSelectionFilteredOnly = true;
    
  }
```

**Comment by don-bluelinegrid** [comment] 2017-07-27 14:32
@ceolter 

> fixed, will be in next release. and yes, both variations are fixed.

Niall, could you give some explanation of how this can work for the remote/server paging scenario?

I don't see any explanation of this here in the "Header Checkbox Selection" section: https://www.ag-grid.com/javascript-grid-selection/#gsc.tab=0  And, there's no reference to this actually working with infinite/virtual row models anywhere in the docs.

And, the idea of a 'select all' checkbox being able to select all rows in an infinite/virtual paging scenario seems to be in contradiction to the concept of infinite/virtual paging, where all rows are not known to the grid.

I have a use case for this, and am not able to make progress and get it working; here is the use case:

Let us assume a data source with a total of 250 rows, and a grid set up with a block size of 50.
1. A grid is displayed, in infinite/virtual scrolling mode; initially 50 rows are loaded.
2. The user clicks a 'select all' checkbox.
3. The user clicks an application action button, for example `Send notification to selected users`.
4. The application then calls `grid.getSelectedRows()` to get the selected row references.
5. The array of selected rows is then used as data in an AJAX request sent to the server API.

The assumption in number 4 above is that the `selectedRows` array will contain all of the 250 rows that would be available from the server.  However, I'm not clear how this is possible, to get actual row references, in an infinite scrolling scenario where only 50 rows have been loaded.  The only way I could see this being possible would be if the `select all` header checkbox triggered a call to `getRows()` with `start-row: 0` and `end-row: 250`, and set the result into the selection-manager framework without setting the data into the grid rows.

Can you please confirm how this is working?  I'm hesitant to spend more time investigated on this, without knowing that it is intended/designed to work.

Thanks,
Don

**Comment by don-bluelinegrid** [comment] 2017-07-27 15:40
Also, after implementing a header checkbox through an alternate mechanism and calling `grid.api.selectAll()`, I'm seeing this error, which makes it appear that `select all` isn't supported in a non-InMemory row model:

```
Uncaught selectAll only available with normal row model, ie not infinite
```

**Comment by m4urer** [comment] 2017-07-31 13:40
I'm having the same problem with the new infinite row model. I was using regular pagination until v8 and now I'm trying to upgrade to v11/12. 

I'm seeing that a lot of behaviour that used to be there with pagination: forEachNodeAfterFilter, headerCheckboxSelection is not available for the new infinite row model, so most of my grids are broken.

I don't get why it was necessary to remove previous functionality. When using pagination=true I think it's pretty clear for the user that both headerCheckboxSelection and forEachNodeAfterFilter get applied over what he's seeing: the current page.

Are you planning of bringing back this functionality for infinite model with paging? It'd be a huge amount of work to always use inMemory and make al the pagination on our side. 

It seems that all these changes have cost a lot of functionality that was already there, am I missing something?

**Comment by Flashwit** [comment] 2017-08-14 22:59
Just seconding m4urer. Was looking to replace our kendo grid with ag-grid but a select all checkbox is a requirement for our use case. It seems to be the only thing missing to complete our transition.

**Comment by seanlandsman** [comment] 2017-10-30 10:35
Hi,

Just to follow up here, if you take a look at https://www.ag-grid.com/javascript-grid-row-models#row-model-summary

The header checkbox only supports the in memory model - this is by design. The reason is that for something like infinite (for example) how would the grid select items it doesn't know about/not yet loaded? 

For anything other than in memory it comes down to the fact that all data may not be available, so the select all functionality here wouldn't have any meaningful action.

**Comment by m4urer** [comment] 2017-10-30 14:22
I understand the problem using the infinite  model. But I'm using server side pagination, and I'm only using infinite because that's the way it's implemented since v9 (as far as I know).
The documentation says "If you were doing server side pagination, we recommend moving to pagination with infinite scrolling as a way of migration to the new mechanism."
So in that case, there's no misunderstanding, there are no more rows that what you are seeing in the current page... 
So unless I can do server side paging with in memory model (I couldn't find that in the examples and probably doesn't go well with what in-memory means), I have lost the ability to use checkbox selection, forEachNodeAfterFilter, etc. So I'm still using v8 because upgrading would break everything.
Any suggestions?

**Comment by codech3ry** [comment] 2017-12-21 02:39
@m4urer  +1

**Comment by rpatel9719** [comment] 2018-03-27 17:31
I am still experiencing the same issue with SELECT ALL as mentioned above. We are not using infinite loop but we are loading all records at once. However, we are only displaying 10 records per page. When I SELECT ALL on page one, all of the records on all pages get selected. I am currently on version 17 and it seems like this issue was fixed in version 8.

**Comment by p-bakker** [comment] 2020-03-04 08:44
Am trying to get a Select All checkbox in the header going while using the Serverside Row Model.

I understand this is not supported by AG Grid, for obvious reasons, but since I control both the front-end as back-end, I can make it work.

The only challenge I have is: how to show a Checkbox in the header and intercept an event when it's changed...

Most suggestions in this case and #46 seem to suggest to create your own checkbox header component. However, I rather not do that, because it would be duplicating a lot of code that is already in the default agHeaderComponent.

I can get the checkbox that AG Grid adds for the selectAll feature to show when using the Serverside Row Model easily, but overridding the ag-hidden CSS class that AG Grid adds to hide the checkbox.

The main problem is intercepting events....

The checkbox uses its own, local, eventservice, so .api/.columApi.addEventListener doesn't work.
Tried addGlobalListener, but the info passed into the listener as arguments doesn't contain any info as to which checkbox was changed, so could be a checkbox on a row or on a header or...

I tried to get access to the implementation of the SelectAll feature in order to modify its behavior, but unfortunately it's all wrapped up in (webpack) closures so no (reliable) way to access it

I then tried to add a eventListener directly on HTML level in the DOM. While I was able to hack that, it forced me to use non-public API (or CSS selectors based on the currently used classes by AG Grid) to get to the right DOM element, which isn't future proof.

I've then tried to see if I could extend the agHeaderComponent, which technically I can get to work, but again requires me to use non-public api, so again not very future proof.

So, I'm wondering if anyone knows a way to get this done in a future-proof way, without having to duplicate code (which in itself is also not very future-proof).

Just to give some ideas:
- Adding a click event listener directly in the DOM:

```
					gridOptions.api.gridPanel.headerRootComp.eGui.addEventListener('click', function(event) {
						// TODO actually do something here
                        console.log('Intercepted')
						return true
					});
```

- Getting to the default agHeaderComponent so I can extend it and register my extended version as the default header component:
```
gridOptions.api.context.beanWrappers.userComponentRegistry.beanInstance.agGridDefaults.agColumnHeader
```

Any thoughts appreciated. Wish there was some public api to get this done, hopefully there is and I just missed it, but have looked extensively and didn't find it

TIA Paul

**Comment by ajaykumarsana** [comment] 2020-12-09 06:20
@ceolter , @riteshwaghela 
is this available now, I see clicking checkbox in header selects records throughout grid rather current page.
Please update!!

**Comment by vandernorth** [comment] 2021-08-24 09:54
@p-bakker did you ever manage to get this to work? I'm looking for the same solution.

**Comment by p-bakker** [comment] 2021-08-24 10:16
We have something that sorta works, with a lot of hacking and it breaks from one AG Grid version to the next

**Comment by ChristopherMat** [comment] 2021-09-23 09:02
Hello,

I'm actually looking for the solution to this issue - I want to select all filtered data (trough entire Grid) only from the current page - is there an out of the box solution to do it or any workaround if not? I'm using ag-grid along with React.

Thanks in advance,
KM

**Comment by jagk** [comment] 2022-04-27 10:52
we need the exact same functionality of selecting only a page in Header checkbox

**Comment by purushottamgour-hotelsoft** [comment] 2022-08-17 10:25
Hello, 

We are looking for enhancement in header checkbox functionality. There should be a way to select all raws only for displayed page. It helps a lot to us to make selection of records based on pagination. Right now whenever we are clicking on header checkbox it is selecting and deselecting all the records for the grid which restricting us to that and we did not find any callback to write custom function for this. We need more dynamic behaviour for header checkbox selection where we can select all displayed page rows as well as we can select all the records for the grid.

Thank you!

**Comment by adv-zl** [comment] 2022-11-29 23:44
Any solution exists?

**Comment by robustadev** [comment] 2025-12-15 08:40
The year is 2025 - this is still a problem...
