### ISSUE TITLE
show column content on hover

### ISSUE THREAD

**Issue by chiptus** [ceolter/ag-grid#415] opened 2015-09-03 08:52 UTC
Can you add a title field or anything similar?
Some time my columns are too small and don't show their whole content, I would like that in that case (and in any case) when I hover it will show a tooltip/popup with the column content. For now I'm adding in cell renderer a span wrapper with the attribute title equals to the cell content.

Thanks in advance and Thanks for this awesome grid!

**Comment by ceolter** [comment] 2015-09-03 11:07
hmmmmm, not sure i like this . . . . having the content as a tooltip sounds great, but is not for everyone, so having to customize it yourself in the colDef makes sense to me.

let me think about it. maybe I put in a colDef.tooltip which would work like valueGetter  . . . . . .

**Comment by dereklin** [comment] 2015-10-07 18:46
When the column is too narrow to show the full content, showing the tooltip on hover is nice.  I would like to have this feature as well.

**Comment by ceolter** [comment] 2015-10-07 18:49
the colDef already supports tooltips. sorry, i should of closed this issue when this was done, i didn't realise the issue was here.

eg
colDef.headerTooltip = 'this is my tooltip';

**Comment by dereklin** [comment] 2015-10-07 18:52
@ceolter but that's for the header only right?  or is it for the content as well?  The content is dynamic...

**Comment by ceolter** [comment] 2015-10-07 18:59
sorry, my fault, i read it as column header. will reopen.

**Comment by patilms16** [comment] 2016-01-12 11:58
Yes. Below column should have tooltip to see the full contents. 
![columncontent](https://cloud.githubusercontent.com/assets/10420421/12262938/52467a64-b951-11e5-8d30-40b6b1c92ced.PNG)

Is there any possible workaround where I can show tooltip?

**Comment by ceolter** [comment] 2016-01-12 14:02
nope. unless you take a fork and implement it yourself.

**Comment by ronanquillevere** [comment] 2016-03-07 11:32
+1 

Should be a per column option IMO.

``` javascript
 columnDefinitions =
[
    {
        headerName: 'Column Header',
        field: 'column',
        enableTooltip : true
    }
]
```

**Comment by chiptus** [comment] 2016-03-07 11:51
+1

**Comment by buremba** [comment] 2016-05-24 22:42
+1

**Comment by ceolter** [comment] 2016-06-01 10:39
just implemented. next release will have it.

new property is colDef.tooltipField, where you provide the field where the tooltip can be found

**Closed by ceolter** 2016-06-01 10:39 UTC

**Comment by buremba** [comment] 2016-06-01 10:45
Thanks!

**Comment by ajaysattikar** [comment] 2016-06-14 23:23
I was able to render custom tooltip with HTML markup on column headers through "headerCellRenderer" and by setting "angularCompileHeaders" true,
Is there any way I can apply custom tooltip (not just HTML title) on content?

**Comment by ceolter** [comment] 2016-06-15 09:06
tooltip was introduced in a recent release.

see tooltip here
https://www.ag-grid.com/javascript-grid-column-definitions/index.php

**Comment by ajaysattikar** [comment] 2016-06-15 22:05
Thanks

**Comment by RamiSh** [comment] 2016-06-22 18:25
Good work.

**Comment by Mithras** [comment] 2016-07-05 22:37
tooltipField covers only the most simple scenarios.
I'd rather have something like tooltipValueGetter(params)

**Comment by harshitgupta** [comment] 2016-11-04 15:18
It works great. 

Is there any way to make it fast. as of now, upon hover overing it, you have to wait for 2-3 seconds until it appears. Thats a lot of time waste. Is there any way i can avoid it?

Thanks a lot.

**Comment by nitoloz** [comment] 2016-11-18 09:48
@harshitgupta I believe it has some delay, because otherwise tooltips would be jumping out on every mouse swipe above the table.
Probably it would be nice to have a  cellTooltipDelay: float; property to change the delay if required

**Comment by re5ive** [comment] 2017-07-20 03:22
can we style this tooltip?

**Comment by Piccirello** [comment] 2017-09-13 16:09
@ceolter Was `tooltipField` removed at some point? I don't see it documented on https://www.ag-grid.com/javascript-grid-column-definitions/index.php.

**Comment by anandSep90** [comment] 2017-09-21 10:49
i cant find the tooltip field in documentation.
https://www.ag-grid.com/javascript-grid-column-definitions/index.php.

**Comment by seanlandsman** [comment] 2017-09-21 11:49
Take a @Piccirello @anandSep90 look https://www.ag-grid.com/javascript-grid-column-properties/ for the latest docs

**Comment by anandSep90** [comment] 2017-09-21 13:05
Yeah the tooltip properties is available in the above link.

`{ headerName: "User Role", field: "userRole", width: 70, editable: true, tooltipField: "userRole", headerTooltip: "User Role"},`

**Comment by meghma** [comment] 2017-10-18 12:57
By default tooltips should be turned on automatically with the cell value when the column width is smaller than what the cell value need to display completely

**Comment by gjenner** [comment] 2017-11-22 14:07
While a few have suggested tooltip styling, or maybe cellTooltipRenderer, there has been no response.  is there a way to style the tooltips?

**Comment by SayingsOlly** [comment] 2017-11-29 21:37
cellTooltipRenderer would be nicer to have.
I add a tooltip in cellRenderer but the problem is the tooltip must be  "display: overflow" to show.
but if setting the cell as overflow, the columns would be affected too.

**Comment by DominicTobias** [comment] 2018-01-24 12:46
Docs are a bit confusing, don't say what type it's expected to return or anything, but it seems ˋtooltipFieldˋ should be an array since it errors with ˋthis.colDef.tooltipField.indexOf is not a functionˋ?

Basically when I shorten a floating point in a cell, I want to show the whole value simply using a html ˋtitleˋ attribute. I would have imagined something like this:

ˋˋˋjs
cellRenderer: params => params.value.toFixed(8),
cellTitle: params => params.value
ˋˋˋ

**Comment by tamarshankolevsky** [comment] 2019-02-11 12:08
if i want ellipsis just when i can't see all the sell content,how can i do it?
i want to enable another tool tip sometimes,all time.

**Comment by shijinmk2006** [comment] 2020-08-20 06:02
Am using Ag grid with vue+typescript 

am getting this error when i use tooltip feature. any help 

![image](https://user-images.githubusercontent.com/4848814/90722618-d013e700-e2d8-11ea-86c1-53bdc1ba4294.png)

**Comment by Samerkassem** [comment] 2020-09-22 11:53
It's not working at all, and I am using your latest release.

```
  getColumnDefs = (fieldsArray) => {
    let columnDefs = [];
    this.tableData = this.data.map((record) => {
      let obj = {};
      fieldsArray.forEach((field) => {
        obj[field] = record[field];
      });
      return obj;
    });

    Object.keys(this.tableData[0]).forEach((key) => {
      let obj = { 
        headerName: this.labels[key], 
        field: key , 
        sortable: true,  
        tooltipField: key
      };
      obj.valueFormatter = (params) => this.formatCells(params.data[key], key);
     
      columnDefs.push(obj);
    });

    return columnDefs;
  };
```

**Comment by KalikiPranathi** [comment] 2022-03-21 10:50
I'm trying to use tooltipField on cellrenderer but its not working

const columns = [
    {
      field: "productName",
      lockPosition: true,
      tooltipField: 'productName',  --> **working as expected**
    },
    {
      field: "history",
      lockPosition: true,
      width:50,
      cellRenderer: 'historyRenderer',
      tooltipField:'history' ---> **not showing the tooltip in this case when I add cellRenderer for column data**
    },
]

Can you please explain where it could have gone wrong?
