### ISSUE TITLE
5.x breaks horizontal scroll 

### ISSUE THREAD

**Issue by connorblack** [ceolter/ag-grid#1090] opened 2016-08-19 11:40 UTC
![grid-fail-generic](https://cloud.githubusercontent.com/assets/1903789/17808779/099d05b2-65e0-11e6-977d-fd064470430b.gif)

Chrome Version 52.0.2743.116 (64-bit)
Mac OSX 10.11.6 (15G31)

**Comment by ceolter** [comment] 2016-08-22 09:25
i don't see anything wrong with this on my win 10 using either chrome of safari. i don't have a mac :(

**Comment by connorblack** [comment] 2016-08-22 13:34
@ceolter it's pretty easy to replicate. Downgrading to 4.x fixes the issue. 

What can I do to help you fix this?

**Comment by loverajoel** [comment] 2016-08-22 18:11
I have the same issue on Chrome in Windows 7.
I can add efforts to resolve it

**Comment by billyvg** [comment] 2016-08-23 00:00
This is also broken for us, we are using a virtualized grid with many columns.

It looks like `ag-header-cell` cells are not being positioned properly, the `left` properties have the correct value, but it's not being rendered the way you want.

**Comment by ceolter** [comment] 2016-08-23 07:55
@connorblack @loverajoel @billyvg i did a lot of style changes with the headers between v4 adn v5, as now the columns are virtualised, the 'left' style is used to place the header cells, whereas before they were just laid out in a flow layout (ie one after the other, starting at the start). i will see if i can reproduce again - however to fix, if you can help, i either need to get it reproduced here, or if you figure out what css is needed to fix it - then i can trust you and just apply it - as long as it's not breaking anything else then i'll release based on what you suggest.

this has got to be a rare issue - something about your environments, maybe some clashing css in your apps? i say this as it has not been widely reported. 25k+ downloads in the last month since v5 was released.

**Comment by ceolter** [comment] 2016-08-23 07:55
is it on any of the online examples? or just happening inside your apps?

**Comment by jeffshaver** [comment] 2016-08-23 14:15
In my case, it was a custom theme I was using. The problem being that the css set `.ag-header-cell` to `position: relative`. Removing that fixed the issue for me

**Comment by connorblack** [comment] 2016-08-23 14:25
I still have the issue even when `.ag-header-cell` isn't `position: relative`

**Comment by connorblack** [comment] 2016-08-23 14:26
@ceolter I unfortunately can't give you access since my project is private

**Comment by billyvg** [comment] 2016-08-23 18:38
@ceolter You're right, we were using ag-grid from npm, but using ag-grid CSS from a different source so it was outdated.

**Comment by light049** [comment] 2016-08-27 16:56
I also meet this issue, I use ag-grid in react.

**Comment by light049** [comment] 2016-08-27 17:41
Sorry, fixed after .ag-header-cell adding position: absolute

**Comment by ceolter** [comment] 2016-08-31 10:57
looks like all issues here were with client code setting css in themes, or using wrong css. so not a grid issue. closing.

**Closed by ceolter** 2016-08-31 10:57 UTC
