### ISSUE TITLE
Grouping rows with complex objects doesn't work with groupDisplayType: groupRows

### ISSUE THREAD

**Issue by tmsdr** [ceolter/ag-grid#9194] opened 2024-11-05 18:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
I took this as the starting point: https://www.ag-grid.com/angular-data-grid/grouping-complex-objects/
The only thing I changed is that I switched groupDisplayType to 'groupRows'.
Here is the Plunker: https://plnkr.co/edit/K2ZoRboKAkmlYGZZ
As you can see, the country names get broken, they all look like: "[undefined] undefined" instead of for example "[HU] Hungary".
As far as I see, in this scenario the value formatter receives the already formatted value as the params.value instead of the raw object value, that is causing the issue.

**Expected behavior**
The value formatter should never receive the already formatted value in params.value.
The example should work not just for the default groupDisplayType, but for 'groupRows' as well.

**Please tell us about your environment:**
Angular - my environment doesn't seem to matter as I could reproduce easily on Plunker too

* **AG Grid version:** latest - 32.3.2 (but older versions too)

* **Browser:** all

* **Language:** all

**Comment by AG-Zoheil** [comment] 2024-12-12 14:47
Hi @tmsdr,

Thanks for reporting this.

This seems to be fixed in the latest version of AG Grid - see here: https://plnkr.co/edit/kndYBwKjIvaVBk1m?open=app.component.ts.

If you are still having issues please provide a reproduction with the latest version and we can have a look.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-12-12 14:47 UTC
