### ISSUE TITLE
Unexpected 

### ISSUE THREAD

**Issue by richardaum** [ceolter/ag-grid#9101] opened 2024-10-21 20:30 UTC
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Reproducible**
https://codesandbox.io/p/sandbox/react-typescript-forked-7t8473?file=%2Fsrc%2FNotWorkingGrid.tsx

https://github.com/user-attachments/assets/958a46d1-e456-4664-8ba9-03a3ba671f06

**Steps**
- Type something on the text field.
- Press the refresh buttons.
- Notice how the cells are prefixed.

**Current behavior**

We're using the `rowModelType = infinite` to load async data inside of a grid. You can check a simplified version of it on the Codesandbox above. 

The issue we have is related the `datasource.getRows` not being aware of external context. Here it is a quote from the docs about it.

> If you call setGridOption('datasource', datasource) the grid will act assuming it's a new datasource, resetting the block cache. However you can pass in the same datasource instance. So your application, for example, might have one instance of a datasource that is **aware of some external context** (e.g. the business date selected for a report, or the 'bank ATM instance' data you are connecting to), and **when the context changes**, you want to reset, but still keep the same datasource instance. In this case, just call setGridOption('datasource', datasource) and pass the same datasource in again.

In the provided example, when passing the `prefix` variable, it looks like its value is not properly being considered, which goes against of the awareness of an external context.

**Expected behavior**
We expect the `datasource.getRows` to be aware of external context. I believe the proper behavior is that `datasource.getRows` is always aware of any external variables, as any function in vanilla Javascript is.

**Please tell us about your environment:**
MacOS, Visual Studio Code, Yarn, Next.js

* **AG Grid version:** X.X.X
32.2.2

* **Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

* **Language:** all

**Comment by AG-Zoheil** [comment] 2024-10-22 15:15
Hi @richardaum ,

Thank you for getting in touch.

This is not a bug but a configuration issue. We do not agree with the expected behaviour. 
The datasource is set into the grid once at the time the grid ready callback is executed. At this point in time, prefix will be bound. For it to update it would need to be scoped correctly

As we do not provide support via GitHub I will be closing this issue here.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-10-22 15:15 UTC
Labels: invalid
