### ISSUE TITLE
Grid Option 'onCellContextMenu' doesn't work in v33.0.1

### ISSUE THREAD

**Issue by ivangrekulovic** [ceolter/ag-grid#9532] opened 2024-12-13 01:06 UTC
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/Dv8o9N9VaCE1Zg97?open=app.component.ts

**Current behavior**
Grid Option 'onCellContextMenu' doesn't work.

**Please tell us about your environment:**

* **AG Grid version:** 33.0.1

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

**Comment by sabahang** [comment] 2024-12-13 10:41
@ivangrekulovic you need to import ContextMenuModule from "ag-grid-enterprise". See here:
https://plnkr.co/edit/jP7thlj8sgptzIHy?open=app.component.ts

However we have decided to separate this logic from ContextMenuModule so that it would work without that module. Hence I have created a ticket for this which follows. Thanks

**Comment by sabahang** [comment] 2024-12-13 11:08
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13705**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed as completed by sabahang** 2024-12-13 11:08 UTC
