### ISSUE TITLE
[row model] Lazy loading of group data

### ISSUE THREAD

**Issue by Pegasuz** [ceolter/ag-grid#678] opened 2016-01-27 15:32 UTC
I would like to be able to:
- Render a small list of groupings (call them categories or such)
- On expand/click of a grouping, load row data from external source and display the newly fetched rows into the grid

Do you have a solution for this? Is this possible?

**Comment by ceolter** [comment] 2016-01-27 15:40
no solution yet. it's lazy loading of the groups.

**Comment by microchip78** [comment] 2016-07-13 23:07
Is there any update on this issue ? Any plan to implement it ?

We are planning to use enterprise version of AG Grid in our analytics product. AG Grid is an awesome product and perfect fit for our application.

But one critical feature of our application is loading massive and indefinite level hierarchical tree data. But we don't want to load all nodes in first call for performance reason. We would like to load just top level nodes when grid load first time, and then when user click on one of the + sign of node, it will expand that node and load its child nodes.

our decision to purchase Enterprise version of AG Grid is depend up on lazy loading of row group feature is available or not, as this is most critical feature of our application.

Please provide any plan or update on that.

Thanks

**Comment by ceolter** [comment] 2016-07-29 11:18
no plan to implement this in the near future, so i cannot commit to it for a sale.

it would take approx one full week to implement it.

if your company is interested in sponsoring this piece of work, then get in touch with accounts@ag-grid.com

otherwise, well you can implement something yourself. create your own cellRenderer for the group column and then implement your own logic for contacting the server when you expand / contract the row.

**Comment by andrss** [comment] 2017-01-06 05:58
Dear @ceolter,  I have a proposal to discuss. When a feature requested, that you do not have immediate plans to implement, why don't you you price this feature out and put this information on your website, so everybody interested can donate towards this particular feature. As soon as enough funds collected you implement the feature and everybody wins. Crowdfunding is very powerful thing!

**Comment by ceolter** [comment] 2017-01-09 11:09
@andrss because we are very very busy building out ag-Grid and making our money from sales of ag-Grid Enterprise licenses. so what we work on is the features we believe will make ag-Grid a better product for our overall customers rather than chasing the short term goals and getting paid directly for features.

these two approaches overlap. sometimes we do take money for particular features. but generally speaking everything we do is with the intention of making ag-Grid better for our current and future customers.

**Comment by ceolter** [comment] 2017-01-23 17:34
tracked b y https://ag-grid.atlassian.net/browse/AG-103

**Comment by ceolter** [comment] 2017-01-25 09:15
duplicate of https://github.com/ceolter/ag-grid/issues/566

**Closed by ceolter** 2017-01-25 09:15 UTC
Labels: enhancement

**Comment by schouti** [comment] 2018-01-04 19:00
@ceolter 

We're using the enterprise edition of ag-grid and I'm looking for the following, How can I achieve this?

**On expand/click of a grouping, load row data from external source and display the newly fetched rows into the grid**

Do we have any solution for this?

**Comment by sumanth1801** [comment] 2018-07-02 06:03
Do we have any solution yet for this?

**Comment by schouti** [comment] 2018-07-02 13:33
@sumanth1801 You can find it in the link below:
https://www.ag-grid.com/javascript-grid-server-side-model/
