### ISSUE TITLE
[filtering] Allow set-filters to update it's values after a data change.

### ISSUE THREAD

**Issue by arikanos** [ceolter/ag-grid#58] opened 2015-04-14 13:52 UTC
Could you please add the behavior, so the checkboxes in set-filters updates when a cell value is edited. Thank you in advance. 

best regards, 

osman

**Comment by ceolter** [comment] 2017-01-23 12:28
tracked by https://ag-grid.atlassian.net/browse/AG-41

**Comment by ceolter** [comment] 2017-01-25 08:52
duplicate of https://github.com/ceolter/ag-grid-enterprise/issues/8
closing

**Closed by ceolter** 2017-01-25 08:52 UTC
Labels: enhancement
