### ISSUE TITLE
Regression: column headers and columns are not aligned

### ISSUE THREAD

**Issue by paripsky** [ceolter/ag-grid#7131] opened 2023-10-10 12:31 UTC
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
As you can see, even in your docs, the right most column has a margin right that makes the column not aligned to the column headers,
see here:
https://www.ag-grid.com/javascript-data-grid/scrolling-scenarios/#auto-height-full-width--pagination
<img width="937" alt="image" src="https://github.com/ag-grid/ag-grid/assets/10563728/55154d5b-5a26-4455-9a37-0a06e0752f99">

**Expected behavior**
The headers and columns should be aligned.

**Please tell us about your environment:**
MacOS 13.0

* **AG Grid version:** X.X.X
30.2.0

* **Browser:**
Chrome

* **Language:** all

The issue is fixed if I downgrade to 30.1.0

**Comment by AG-Zoheil** [comment] 2023-10-10 14:09
Hello @paripsky,

Thank you for reporting this - much appreciated!

We are aware of this issue and have already fixed it. It will be released with our next version.
You can track it with the following reference in our pipeline/changelog: **AG-9461**

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2023-10-10 14:09 UTC
Labels: AG-9461

**Comment by myleslee** [comment] 2023-11-20 08:45
@AG-Zoheil 
 
The issue can be reproduced on 
- AG `30.2.1`
- Chrome Version 119.0.6045.159 (Official Build) (x86_64)
- MacOS Sonoma 14.1.1 (when System Settings > Appearance > Show scrollbars > Automatically based on mouse or trackpad)

<img width="1020" alt="Screenshot 2023-11-20 at 16 19 08" src="https://github.com/ag-grid/ag-grid/assets/108758/c4b25d48-bdfe-4ce3-96ea-b6453bb739f7">

<img width="491" alt="Screenshot 2023-11-20 at 16 41 20" src="https://github.com/ag-grid/ag-grid/assets/108758/8c2560e0-f7ba-4e0e-bc2b-b5b3a8bbc860">

Do I need to create a new issue or you can just reopen `AG-9461` to follow up?

Thank you!

**Comment by myleslee** [comment] 2023-11-20 12:29
@AG-Zoheil  It's weird. The issue is gone after I rebooted my MacBook. So pls ignore my last post. Thanks.

**Comment by AG-Zoheil** [comment] 2023-11-30 09:17
Thanks @myleslee,

V31 has now been released successfully and included **AG-9461**.

Kind regards,
Zoheil
