### ISSUE TITLE
[rows] grid has max numbers of rows in can show, due to max div height

### ISSUE THREAD

**Issue by jonbcard** [ceolter/ag-grid#1026] opened 2016-07-19 18:24 UTC
I have a grid with ~100k in-memory rows, and when scrolling to the bottom in IE11 or Edge browsers it looks like about half the data is missing. Checking the agGrid site example, it looks like the same issue is present.

![image](https://cloud.githubusercontent.com/assets/497168/16961534/259b25c0-4dab-11e6-9a09-3322c313ce64.png)

As shown in the screenshot, I've sorted by name and I've scrolled to the bottom of the grid, but its only showing atheletes that start with 'L'.

I tested this on 5.0.2, and it looks like the agGrid example is using the same.

**Comment by seanlandsman** [comment] 2017-01-24 10:41
tracked by AG-131
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-25 09:17
duplicate of https://github.com/ceolter/ag-grid/issues/226

**Closed by ceolter** 2017-01-25 09:17 UTC
Labels: enhancement
