### ISSUE TITLE
getFilterModel and setFilterModel inconsistent on blank filter

### ISSUE THREAD

**Issue by IS-smcleod** [ceolter/ag-grid#485] opened 2015-10-07 19:55 UTC
For a column, set to only show blank entries, getFilterModel will return:

``` javascript
{ column: [ "null" ] }
```

but setFilterModel expects:

``` javascript
{ column: [ null ] }
```

**Comment by ceolter** [comment] 2015-10-07 20:57
none of my examples have blank entries!! i'll need some time to look into this a bit deeper.

**Comment by rhnatiuk** [comment] 2015-10-14 04:31
Is it the same issue in IE11? When clearing the quick filter text box with its cross-on-the-right-of-the-text-box (whatever that thing is called), the filter is not resetting, despite the value of the text box is gone. On the other hand, when clearing the value using delete or backspace keys, the filter will correctly reset to empty when the text box value is gone. You can reproduce it straight in your first sample grid on the main page.

**Comment by ceolter** [comment] 2015-10-14 09:36
> When clearing the quick filter text box with its cross-on-the-right-of-the-text-box

this isn't a grid issue, that's (if using angular) angularjs not updating the scope.

**Comment by rhnatiuk** [comment] 2015-10-14 09:46
Guessed it, but hoped that I am wrong! :)

Any ideas for workarounds?

At the moment I "fixed" it by removing the offending icon using CSS:

::-ms-clear {
	display: none;
	width: 0;
	height: 0;
}

(I think display: none is the only required part; also, you can add more specific selector, e.g. input[type=text] before, if you wish)

**Comment by ceolter** [comment] 2015-10-14 09:49
no idea, sorry. but given it's not a grid issue, i'm not very motivated towards finding out to be honest!!

**Comment by ceolter** [comment] 2017-01-18 12:24
not a grid issue, so closing.

**Closed by ceolter** 2017-01-18 12:24 UTC

**Comment by nickytonline** [comment] 2017-02-16 21:30
I can confirm this behavior. The workaround for now is to just to map your filter model before you set it.

```
function mapNullsInFilterModel(filterModel) {
  const mappedFilterModel = {};

  Object.keys(filterModel).forEach(key => {
    const currentFilter = filterModel[key];

    mappedFilterModel[key] = currentFilter.map(f => f === 'null' ? null: f);
  });

  return mappedFilterModel;
}
```

and then e.g.
```
// const yourFilterModel = {...}
this.api.setFilterModel(mapNullsInFilterModel(yourFilterModel))
```

this is required because when ag-grid looks at its array of `uniqueValues`, the value stored is `null`, not `"null"`

**Comment by nickytonline** [comment] 2017-02-16 21:33
I can throw a PR up for this if you'd like, but it also means that is someone puts up an actual string with the text, `"null"`, there would be no way to differentiate them. Having said that, I think that scenario is an extreme edge case.

**Comment by nickytonline** [comment] 2017-02-17 14:03
My fix works, but it's actually for the ag-grid enterprise set filter. I will open an issue over there.

**Comment by nickytonline** [comment] 2017-02-17 17:35
https://github.com/ceolter/ag-grid-enterprise/issues/109
