### ISSUE TITLE
[grid height] allow grid to adjust it's height based on number of rows

### ISSUE THREAD

**Issue by ricklxm** [ceolter/ag-grid#1105] opened 2016-08-26 09:52 UTC
I mean, the grid will auto increase its height if data rows count increase

**Comment by ericmhalvorsen** [comment] 2016-08-29 14:46
This is actually possible with plain CSS - the grid is expecting the containing div to have an explicit height set. If you leave the height rule off and instead only set a min-height / max-height the grid will dynamically size based on those limits.

Here's a plunker showing what i mean: https://plnkr.co/edit/exxdYdMBomYtnRn17aWS?p=preview

Edit the 'totalRows' variable to adjust the data size.

**Comment by ricklxm** [comment] 2016-08-30 05:34
Thanks, @ericmhalvorsen , I've tried to leave the height rule off. But it will lead to another weird behavior: the table height will increase constantly if I set the theme as 'ag-fresh' (if set as other theme, it works well):

![1](https://cloud.githubusercontent.com/assets/4877955/18077153/1aa7d8d0-6eb6-11e6-996c-3d2de04caeb9.png)
![2](https://cloud.githubusercontent.com/assets/4877955/18077157/20eb6d74-6eb6-11e6-9961-63795cb87c4b.png)
![3](https://cloud.githubusercontent.com/assets/4877955/18077158/25dcd8b8-6eb6-11e6-85d2-17a2130b47c0.png)
![4](https://cloud.githubusercontent.com/assets/4877955/18077159/29710328-6eb6-11e6-9f6c-33703f0149c4.png)

**Comment by ceolter** [comment] 2016-08-31 13:13
the grid isn't designed for automatically growing in size. something i plan but is not scheduled work yet.

**Comment by ceolter** [comment] 2016-08-31 13:13
pretty sure this is a duplicate issue btw, has been asked for before.

**Comment by ricklxm** [comment] 2016-09-01 02:32
Checked open issues and the non-stop growing issue is reported in #1056

**Comment by seanlandsman** [comment] 2017-01-24 10:45
tracked by AG-136
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-26 16:19
duplicate of this one:
https://github.com/ceolter/ag-grid/issues/801
so closing

**Closed by ceolter** 2017-01-26 16:19 UTC
Labels: enhancement

**Comment by smile2014** [comment] 2018-05-07 01:03
@ricklxm 动态设置 ag-grid 的高度你搞定没，我也有这样需求，能指点下不

**Comment by wcldyx** [comment] 2020-08-25 15:02
> @ricklxm 动态设置 ag-grid 的高度你搞定没，我也有这样需求，能指点下不

me too
