### ISSUE TITLE
[selection] shift-select for virtual paging

### ISSUE THREAD

**Issue by CReich02** [ceolter/ag-grid#1051] opened 2016-08-02 19:51 UTC
I did post this on the forums but have not gotten any replies yet so I am adding it here.
https://ag-grid.com/forum/showthread.php?tid=3995

I believe this is a bug in ag-Grid. click-shift-click to select multiple rows is not currently working in ag-grid when virtual paging is enabled.
It works fine here with static data, [Example - Multiple Row Selection](https://ag-grid.com/angular-grid-selection/index.php).
But when virtual paging is enabled and rowSelection is still set to 'multiple' it does not work, Simple [Example - No Sorting or Filtering](https://www.ag-grid.com/javascript-grid-virtual-paging/index.php).

Ctrl-click to select multiple rows and deselect rows still works but click-shift-click does not work.

Here is a example of two grids where it works on one but not on the other, the only difference is that the one that doesn't work has rowModelType: 'virtual'. 
http://codepen.io/anon/pen/yJEpkY

**Comment by killyosaur** [comment] 2016-08-03 10:12
This was fixed as of version 5.0.4 of the grid.

**Comment by ceolter** [comment] 2016-08-15 14:49
correct it doesn't work - but i didn't intend for it to work. it is possible for the page the last selected row was in to be no longer loaded due to the purging of the cache, so the pattern breaks down when used with virtual paging. i'll leave this issue here as i man get time to code something up to support it - however it would be a new feature, not a bug fix.

**Comment by rkait** [comment] 2016-10-07 20:38
Thanks @ceolter for the consideration of this feature.

As far as you know, would there be an issue with iteration using `forEachNode` in the function for selection for virtual paging? On my initial try, it seems that editing `rowNode.js` like this allows `SHIFT` selection to work:
```javascript
RowNode.prototype.setSelectedParams = function (params) {
 // ...
 // remove line for checking if row model is normal
   if (rangeSelect) {
     var newRowClicked = this.selectionController.getLastSelectedNode() !== this;
     var allowMultiSelect = this.gridOptionsWrapper.isRowSelectionMulti();
     if (newRowClicked && allowMultiSelect) {
       this.doRowRangeSelection();
       return;
     }
  }
  // ...
```
```javascript
RowNode.prototype.doRowRangeSelection = function () {
  // ...
  // add logic to switch iterator function based on rowModel type
  var rowModelNormal = this.rowModel.getType() === constants_1.Constants.ROW_MODEL_TYPE_NORMAL;
  var iterator = rowModelNormal ? 'forEachNodeAfterFilterAndSort' : 'forEachNode';
  this.rowModel[iterator](function (rowNode) {
  // ...
```

**Comment by ceolter** [comment] 2016-10-12 10:01
forEachNode wont work because:
1) the rows are not iterated in order they appear - the pages in the cache are gone through in no particular order (from looking at the code, i think it goes through them alphabetically, so page 1, 11, 12, 2, 3, 4, 5, etc)
2) the pages can be purged, so pages can be missing, depending on how you have it configured and what scrolling you have done.

**Comment by seanlandsman** [comment] 2017-01-24 10:43
tracked by AG-134
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by makinggoodsoftware** [comment] 2017-07-24 07:52
Hi,

Just to let you know that this ticket has been released as part of v12. https://www.ag-grid.com/change-log/changeLogIndex.php

Thanks

**Closed by makinggoodsoftware** 2017-07-24 07:52 UTC
Labels: enhancement
