### ISSUE TITLE
[Cell Editing] [React] After stop cell editing with cellEditorPopup grid focuses cell in next row

### ISSUE THREAD

**Issue by Azimyth** [ceolter/ag-grid#8958] opened 2024-10-09 14:33 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- add enterNavigatesVerticallyAfterEdit prop to the grid
- assigned cellEditorPopup: true to any editable cell
- start editing cell
- click outside grid
- focus event fires twice on the cell in next row

I rendered focused cell indexes, so you will be able to catch focus events.
Also I added highlighting on cell focusing

Plunker: https://plnkr.co/edit/b1MtdR8dkUcC1nnp?open=index.tsx&preview
Record: https://github.com/user-attachments/assets/945d3a73-10f9-4fef-b622-72f0b037ed19

**Current behavior**

If you stop editing via 'Enter' or 'Esc' buttons it works fine. 
When you stop editing with outside click grid fires focus event twice with wrong cell.
It behaves such way only in combination with **enterNavigatesVerticallyAfterEdit** and **cellEditorPopup**.
If you remove some of these props it will work as expected.

**Expected behavior**

I suspect it's a bug, in this scenario, it should not focus any cell or at least focus correct one (edited cell).

**Please tell us about your environment:** Windows 11 Enterprise (23H2)

* **AG Grid version:** 32.1.0

* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

* **Language:** [React 18]

**Comment by sabahang** [comment] 2024-10-10 15:36
@Azimyth As per docs `enterNavigatesVerticallyAfterEdit` is supposed to imitate an Excel like behavior where focus is moved to next row after exiting Edit mode. Does this answer your question?

**Comment by Azimyth** [comment] 2024-10-11 09:00
@sabahang, description from the [doc](https://www.ag-grid.com/react-data-grid/grid-options/#reference-editing-enterNavigatesVerticallyAfterEdit): 

> Set to true along with enterNavigatesVertically to have Excel-style behaviour for the ↵ Enter key, i.e. pressing the ↵ Enter key will move down to the cell beneath. Default: false.

It means that only Enter key will move down and focus cell underneath. Cell with applied `cellEditorPopup: true` on it behaves a way different than others.

If you check plunker you will see that other cells don't fire focus event after stop editing by outside mouseclick.

**Comment by sabahang** [comment] 2024-10-14 10:08
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-13149 cellEditorPopup causes onCellFocused to be called when losing focus**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed as completed by sabahang** 2024-10-14 10:08 UTC
Labels: AG-13149

**Comment by SamihIsHis** [comment] 2025-08-21 14:46
Just found this in our app after we upgraded to ag grid v33.

It's worse than the above though:

If you have enterNavigatesVerticallyAfterEdit: true and you click any editable cell, you get a single event.

If you then click any editable cell **above** the currently editing one, you get a focus event for the cell clicked, but also another one for the next cell (below).

I guess not many are using this option in conjunction with cell focus events but it could do with being fixed after almost a year.
