### ISSUE TITLE
fullWidthCellRendererFramework does not appear to work

### ISSUE THREAD

**Issue by Siern** [ceolter/ag-grid#1182] opened 2016-10-06 15:04 UTC
When a react component is specified using "fullWidthCellRendererFramework" rather than "fullWidthCellRenderer" (using the factory method "reactCellRendererFactory"), then the grid reports a warning and does not render the full row using the component.

> ag-Grid: you need to provide a fullWidthCellRenderer if using isFullWidthCell()

I have tried with 6.0 and 6.1.

Please refer to my stackoverflow for an example.  The response from Sean seem to indicate that he did not notice it was more-or-less a question that was inferring a fault with the new grid framework options.

[stackoverflow report](http://stackoverflow.com/questions/39708491/ag-grid-full-width-rows-does-not-appear-to-work-with-react-componentsl)

**Comment by ceolter** [comment] 2016-10-12 09:03
i've checked the code - i don't see why it's not working. if you can provide a plunker with it not working, we can check.

are you sure you are using the React component of ag-Grid? ie <AgGridReact> ??

**Comment by Siern** [comment] 2016-10-14 12:26
`import {AgGridReact} from 'ag-grid-react';`
and in my page's render:
```
            <div style={{height: '100%'}} className="ag-blue">
                <AgGridReact {...gridProps}/>
            </div>
```

as far as plunker, I'll see if I get time to attempt to build a sample.

**Comment by harr041** [comment] 2016-10-24 20:43
any update on this? not working for me either.

**Comment by harr041** [comment] 2016-10-24 22:10
Looks like when mounting AgGridReact, the gridOptions that are passed in don't contain fulWidthCellRenderFramework. I looked in componentUtil.js and saw that none of the CellRendererFramework options are listed under FUNCTION_PROPERTIES. When I add, the cells render correctly.

**Comment by XuluWarrior** [comment] 2016-10-26 13:29
I just came across this issue myself.  It may be an issue with ag-grid-react rather than ag-grid as if I pass the fullWidthCellRendererFramework value in the gridOptions property rather than using the fullWidthCellRendererFramework property directly, I get the expected behaviour.

**Comment by ceolter** [comment] 2016-10-31 14:42
@harr041 thanks for the feedback, i believe that was the issue. i've made the change, will be in the next release. basically groupRowRendererFramework, groupRowInnerRendererFramework and fullWidthRowRendererFramework were getting ignored when getting set as properties in Angular 2 and React.

**Closed by ceolter** 2016-10-31 14:42 UTC
