### ISSUE TITLE
Infinite (looping) getRows requests when sorting on certain columns and making a pagination request.

### ISSUE THREAD

**Issue by icicle159** [ceolter/ag-grid#8978] opened 2024-10-11 15:59 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1.) We are using angular v18
2.) I have a grid configuration with the following column definitions:
{
   field: 'viveStatus',
   headerName: 'VIVE Status',
   flex: 1,
   hide: false,
   filter: 'agSetColumnFilter',
   tooltipField: 'viveStatus',
   allowedAggFuncs: [],
   enablePivot: true,
   filterParams: {
     values: [
       'Approved',
       'Suspended',
       'Inactive',
       'Registering',
       'Awaiting Payment',
       'Registered',
       'Reviewing',
       'Renewing',
       'Site Conditional',
       'Compliance Exempt',
       'Business Verified',
       'Non-Verified'
      ]
    }
  },
  {
    field: 'statusDate',
    headerName: 'Status Date',
    flex: 1,
    hide: false,
    filter: 'agDateColumnFilter',
    tooltipField: 'statusDate',
    cellDataType: 'date',
    allowedAggFuncs: []
  }

3.) We use the server side row model to pull additional data from our server when new data is needed.
4.) We have various grid components which extend a "base grid" component. This "base grid" component
      contains various "set up" logic for the grid initialization.
5.) The column definitions in step 2 (above) are for a grid we've defined as the "CompanyVendors" grid in our application.
6.) The "CompanyVendors" grid initializes a ServerSideDataSource as follows:
this.ServerSideDataSource = {
      getRows: (params: IServerSideGetRowsParams) => {
        const { request } = params;

        const queryObject = this.constructGridQuery({ request });

        const { pivotCols, pivotMode, startRow, endRow } = request;

        (() => {
          if (pivotCols.length > 0 && pivotMode) {
            // We may be able to supply this data to the query below instead of double-querying for
            // pivot column information.
            return this.CompanyVendorService.getCompanyVendorPivotColumnHeaders(queryObject);
          }
          return of(null)
        })().subscribe({
          next: (pivotColumnHeaders: null | string[]) => {
            this.CompanyVendorService.getCompanyVendors(queryObject)
              .subscribe({
                next: (CompanyVendors: CompanyVendor[]) => {
                  const successObject: {
                    rowData: any[],
                    pivotResultFields?: string[]
                  } = {
                    rowData: CompanyVendors,
                  };
                  
                  if (isArray(pivotColumnHeaders)) {
                    Object.assign(successObject, { pivotResultFields: pivotColumnHeaders });
                  }

                  params.success(successObject);
                },
                error: (error) => {
                  console.log(error);
                  params.fail();
                }
              });
          }
        });
      }
    };

7.) This line in particular is from a function extended from our "base grid" component:
const queryObject = this.constructGridQuery({ request });

8.) The "constructGridQuery" function accepts an IServerSideGetRowsRequest parameter (called request) and operates as follows:
  // This is used to construct a query object from grid information to be passed
  // to a backend service.
  constructGridQuery(
    gridInformation: { request: IServerSideGetRowsRequest }
  ) {
    if (!this.GridApi) {
      throw new Error('Grid Api has not been registered');
    }

    if (!this.gridType) {
      throw new Error('Missing Grid Type parameter.');
    }

    if (!this.columnDefs) {
      throw new Error('Missing Column Definitions for grid.');
    }

    const { request } = gridInformation

    const additional: {
      loadAllData: boolean,
      request: IServerSideGetRowsRequest,
      queryData?: { [key: string]: any },
      externalFilters?: Map<string, any>,
      suppressFieldDotNotation?: boolean,
      UniversalSearch: { text: string }
    } = {
      loadAllData: this.loadAllData,
      request,
      suppressFieldDotNotation: this.suppressFieldDotNotation,
      UniversalSearch: this.UniversalSearch
    };

    // Apply external filters to the query. External filters are filters that happen outside of the grid.
    if (this.Filters.size > 0) {
      Object.assign(additional, { externalFilters: this.Filters });
    }

    if (this.mergedQueryData) {
      Object.assign(additional, { queryData: this.mergedQueryData });
    }

    const columns = this.GridApi?.getColumns();

    if (!columns) {
      throw new Error('There was an error retrieving column state.');
    }

    this.CurrentGridStateQuery = this.GridService.convertGridDefinitionToQuery(this.gridType, columns, additional);

    this.gridQueryChanged.emit({ GridQuery: this.CurrentGridStateQuery, GridRequest: request });

    return this.UtilityService.stringifyObjectsInQueryObject(structuredClone(this.CurrentGridStateQuery));
  };

9.) This line in particular: this.GridService.convertGridDefinitionToQuery(this.gridType, columns, additional);
      converts the grid's request data, as well as additional data provided by our external components, into query data
      that our backend service accepts and processes.

10.) The query data generated by this function:
this.GridService.convertGridDefinitionToQuery(this.gridType, columns, additional) 
is passed to this function in step 6 (above): 
this.CompanyVendorService.getCompanyVendors(queryObject)

11.) The this.CompanyVendorService.getCompanyVendors(queryObject) sends a request to our backend, which processes the query data, and returns an appropriate response to the front end. This response is then consumed by: params.success(successObject);

12.) Everything has been working fine, until I attempted to sort on the 'viveStatus' column defined in step 2.

13.) After sorting (ascending or descending) on the 'viveStatus' column and scrolling down the grid to trigger the pagination request to load more data (from infinite scroll), the grid begins to repeatedly request more data from our server from the getRows function defined in the ServerSideDataSource. The requests stop if the user scrolls to the top of the grid.

14.) To further complicate the issue, when sorting on the 'statusDate' column (ascending or descending) and scrolling down the grid to trigger a pagination request, no such 'infinite request' loop happens.

15.) My local database contains 482 'CompanyVendor' records.

16.) Our 'base grid' html template is defined as:
<ag-grid-angular
    style="width: 100%; height: 100%"
    class="ag-theme-alpine vive-grid"

    [debug]="true"

    [columnDefs]="columnDefs"
    [getMainMenuItems]="getMainMenuItems"
    [defaultColDef]="defaultColDef"
    [rowData]="rowData | async"
    [rowSelection]="rowSelectionType"
    [animateRows]="true"
    [rowModelType]="rowModelType"
    [groupDisplayType]="groupDisplayType"
    [suppressFieldDotNotation]="suppressFieldDotNotation"
    [sideBar]="sideBar"
    [getContextMenuItems]="GetContextMenuItems"
    [pagination]="pagination"
    [paginationPageSize]="paginationPageSize"
    [context]="context"
    [components]="components"
    [getRowId]="getRowId"
    [rowMultiSelectWithClick]="rowMultiSelectWithClick"
    [suppressRowClickSelection]="suppressRowClickSelection"
    [isRowSelectable]="isRowSelectable"
    (gridReady)="onGridReady($event)"
    (rowDataUpdated)="onRowDataUpdated($event)"
    (modelUpdated)="onModelUpdated($event)"
    (firstDataRendered)="onFirstDataRendered($event)"
    (selectionChanged)="onSelectionChanged($event)"
    (rowSelected)="onRowSelected($event)"
    (newColumnsLoaded)="onNewColumnsLoaded($event)"
    (storeRefreshed)="storeRefreshed($event)"
    (filterChanged)="filterChanged($event)"
    (rowClicked)="gridRowClicked($event)"
  ></ag-grid-angular>

17.) At no point during the creation of the query data for our backend to receive are we modifying any option, definition, or grid-related property which may trigger an infinite request loop.

18.) The 'viveStatus' column is an ENUM field within our database. Various values defined in the ENUM field show up repeatedly on CompanyVendor records. For example: 50 CompanyVendor records may have a 'viveStatus' of 'Approved', and another 120 CompanyVendor records may have a value of 'Suspended', and so forth. I have a sneaking suspicion the infinite reload request may have something to do with these repeated values, but it's just a hunch. It may also have something to do with how the ag-grid expects the columns to be sorted (ascending, alphabetically) whereas our ENUM field sorts the data based on how the values appear in the ENUM definition.

19.) This bug happens in our development environment and in our QA environment. We have not released to production.

20.) With the 'debug' option turned on in the grid, the console is production statements like this when pagination requests are made:
AG Grid: RowNodeBlockLoader - printCacheStatus: activePageLoadsCount = 0, blocks = {"0":{"blockNumber":0,"startRow":0,"endRow":100,"pageStatus":"loading","loadedRowCount":98},"1":{"blockNumber":1,"startRow":100,"endRow":200,"pageStatus":"loaded","loadedRowCount":100}}

It is bizarre that block '0' loaded a row count of 98 rows, whereas the 'network' tab (in the browser's dev tools) shows the request response contains 100 records. Moreover, I'm not entirely sure why the grid is attempting to load the first block again, when the pagination request should only be loading the second block of records.

21.) Normally the 'CompanyVendors' grid contains more than the 2 columns listed above, however for simplicity's sake, I have boiled it down to 2 columns.

**Current behavior**
Sorting on certain columns, when using the Server Side Row Model, and scrolling down to trigger a pagination request from the 'getRows' function intermittently triggers an infinite loop of requests. 'Intermittently' in this case means it doesn't always happen on the first pagination request. It may happen on the first request, second request, third request... etc. Some columns do not trigger this infinite request loop.

**Expected behavior**
Sorting on any grid column with the Server Side Row Model and making a pagination request should only call 'getRows' once.

**Please tell us about your environment:**
I am using:
1.) A 2020 Macbook Pro running OS: Sonoma 14.4.1
2.) Angular Version: 18.2.6
3.) NodeJS Version: 18.20.2
4.) ExpressJS Version: 4.21.0
5.) MySql Database Version: 5.7.31
6.) AG Grid Version: 32.2.2

* **AG Grid version:** 32.2.2
I have read the AG Grid changelog as well as update my version of AG Grid to 32.2.2 and this did not fix the issue.

* **Browser:**
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
1.) Typescript Version: 5.4.5
2.) Ecmascript 2020

* **Additional:
Please let me know if you need anything else from me. I have attached a video showing the issue occurring. It's always possible I have goofed something up in the code, and this very well could be an issue caused by me. Though, after several hours of exhaustive searching, I cannot pinpoint anything we're doing that may have caused this bizarre looping request behavior. Thanks again.

https://github.com/user-attachments/assets/9eba7c6b-531a-46b6-b6b6-f595762c9189

**Comment by AG-Zoheil** [comment] 2024-10-14 09:53
Hi @icicle159,

Thank you for submitting this on Github.

The features you are using are enterprise features. I would encourage you to raise this via our [support portal](https://ag-grid.zendesk.com/hc/en-us) if you do have an active AG Grid Enterprise licence and our dedicated team will be ready to help.

Please also note when getting in touch, the best route to getting help with your issue is to provide our enterprise team with a reproducible online example (like a plunker) so that they can replicate and investigate the behaviour you are reporting.

That would be the most efficient way for you to get assistance with this.

In light of the above, I will be closing this issue here, as we do not provide support on GitHub.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-10-14 09:53 UTC

**Comment by ChristianKlimabrz** [comment] 2024-10-18 07:53
Same here. It's not easy to reproduce the issue. Is there any way to follow a ticket or track the progress?

**Comment by ChristianKlimabrz** [comment] 2024-10-19 07:11
We have identified the cause of the issue. We had two rows with the same ID. The problem was with our backend, which delivered two pages containing the same dataset during pagination. It's unfortunate that the grid behaves oddly in this situation and doesn't detect it, providing a more understandable error message. However, fundamentally, this is not an issue with AG-Grid.
