### ISSUE TITLE
IE11 find-in-page for offscreen column breaks grid column header alignment

### ISSUE THREAD

**Issue by AvishekNath** [ceolter/ag-grid#835] opened 2016-04-13 15:35 UTC
Using IE11 "find in page" functionality (Ctrl / Cmd + F, usually) to search for column heading text for a column that is offscreen to the right when the grid is horizontally scrollable causes the header row to be scrolled while the body is not scrolled to match. This causes the header row to be permanently out of alignment with the body, and it is not possible to fix manually.

Even I tried adding scroll event in '.ag-header' div container, but it did not really worked. As, '.ag-header' is not a scrollable container, so 'scroll' event do not trigger.

Can you suggest some way to fix it in IE.
<img width="960" alt="ag-grid_issue" src="https://cloud.githubusercontent.com/assets/1690086/14499415/cfddc376-01bb-11e6-8bfc-493033d74f93.png">

**Comment by ceolter** [comment] 2016-04-14 09:10
no solution yet.

duplicate of this, so closing:
https://github.com/ceolter/ag-grid/issues/571

**Closed by ceolter** 2016-04-14 09:10 UTC

**Comment by AvishekNath** [comment] 2016-04-14 09:21
Hi Niall, 

Can u please suggest some work around.. I will try it out..

Thanks,
Avishek

**Comment by ceolter** [comment] 2016-04-14 09:30
i have no suggested workaround. sorry.
