### ISSUE TITLE
Project test coverage?

### ISSUE THREAD

**Issue by hunthunthunt** [ceolter/ag-grid#729] opened 2016-02-22 10:18 UTC
I've just started using ag-grid for a project and it's been pointed out by a colleague that test coverage is pretty much non-existent.

Can you please confirm if this is the case, or are we missing something?

Secondly, how receptive is the project to contributions around this, is it something that's already underway or on the roadmap? 

Thanks

**Comment by noherczeg** [comment] 2016-02-22 14:57
He wrote back in the old days somewhere that He won't be providing tests, but the policy he forces on e.g. pull requests requires everyone to update relevant examples and docs. @ceolter am I right?

**Comment by AkosLukacs** [comment] 2016-02-23 08:37
#10 is the earlier test-releated issue

**Comment by hunthunthunt** [comment] 2016-02-23 09:48
Thanks @noherczeg & @AkosLukacs :+1:

**Comment by ceolter** [comment] 2016-02-23 09:51
i am not writing tests and don't intend them any time soon. again due to my massive re-factoring efforts i'm doing and my style of development.

before i release, i do full manual regression testing. all of the features i implement are present in the documentation examples which i use for my manual testing, so in effect the documentation acts as my regression test script.

historically, the grid is very solid, more solid than other projects with lots of tests.

if your colleague uses this as a measure of good quality code, you should use ui-grid, it's poor in comparison IMO, but you can sleep well knowing the poor code has lots of tests!

ps closing this, as it's a duplicate

**Closed by ceolter** 2016-02-23 09:51 UTC

**Comment by hunthunthunt** [comment] 2016-02-23 09:55
Thanks @ceolter, appreciate your considered response :)
