### ISSUE TITLE
[FEAT] Column width: auto

### ISSUE THREAD

**Issue by TravisTX** [ceolter/ag-grid#41] opened 2015-04-05 01:03 UTC
Allow columns to resize themselves to fit the content of the longest cell.  Suggested column definition syntax:
`{ displayName: 'Url', field: 'url', width: 'auto' }`

**Comment by amcdnl** [comment] 2015-04-06 18:22
Possible dupe of #7 ?

**Comment by TravisTX** [comment] 2015-04-06 18:29
I don't think it's a dupe.
#7 is suggesting making columns expand to fill the width of the parent div.
#41 is suggesting making a column expand to fit it's own content.

**Comment by amcdnl** [comment] 2015-04-06 18:33
Ah, gotcha.  Thats gonna be tough to achieve performantly.

**Comment by ceolter** [comment] 2015-04-06 18:46
Reckon we can break some rules to make it quick, eg assume fixed pixels per
text character (assumes plaintext default cell rendering), or could just
sample first 100 rows (render them off page, get max width of result).

**Comment by amcdnl** [comment] 2015-04-06 22:12
Ya, but if you enable templates and whatnot it gets expensive fast and bug prone.  Does slickgrid do this?

**Comment by ceolter** [comment] 2015-04-06 22:17
yes slickgrid has it:
http://stackoverflow.com/questions/6794656/how-do-i-autosize-the-column-in-slickgrid

also excel has it, ie double-click the RHS of the column header, would be
pretty cool if the grid did this.


On 6 April 2015 at 23:12, Austin <notifications@github.com> wrote:

> Ya, but if you enable templates and whatnot it gets expensive fast and bug
> prone. Does slickgrid do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/41#issuecomment-90261264>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by amcdnl** [comment] 2015-04-06 22:20
Looks like it does force fill and autosize!  Just steal their code ;)

It would be really tricky to get 'row height' sizing with infinite scrolling!

**Comment by ceolter** [comment] 2015-04-06 22:24
not doing auto-row height - that's fixed - just width

don't think i'll take their code, just get inspired by the ideas!!

On 6 April 2015 at 23:21, Austin <notifications@github.com> wrote:

> Looks like it does force fill and autosize! Just steal their code ;)
>
> It would be really tricky to get 'row height' sizing with infinite
> scrolling!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/41#issuecomment-90262746>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment] 2015-04-19 04:21
:+1: This would be great

**Comment by ocombe** [comment] 2015-07-09 16:35
This would be so cool, any news on this @ceolter ?

**Comment by ceolter** [comment] 2015-07-09 16:41
no closer to doing this i'm afraid. still on my to-do list.

**Comment by chiptus** [comment] 2015-07-12 05:03
:+1:

**Comment by piernik** [comment] 2015-08-13 06:29
+1

**Comment by Gratouille** [comment] 2015-08-19 14:08
+1

**Comment by nileshmali** [comment] 2015-10-06 17:47
Any plans for this feature?

**Comment by ceolter** [comment] 2015-10-06 20:54
yup i still plan to do it, but i don't have the work scheduled right now.

**Comment by greglockwood** [comment] 2015-11-17 22:44
When you get around to doing this, I would love to see at least 4 "modes" for auto-sizing of columns.
* None (current behaviour)
* Fit Header (just wide enough to fit heading text in)
* Fit Contents (just wide enough to fit largest contents)
* Fit Header & Contents (wide enough to show all data without truncation)

I assume fitting the contents in will be the hardest, since that could change as new data gets loaded in. It would also be the slowest, due to having to measure each cell to get the width.

**Comment by amcdnl** [comment] 2015-11-18 14:13
@greglockwood  you should chk out my project: https://github.com/Swimlane/angular-data-table ... its got some unique sizing techniques

**Comment by ceolter** [comment] 2015-11-18 17:29
@greglockwood @amcdnl lol no worries Austen. if someone thinks another grid is a better choice for them, that's fine with me. takes the pressure of some features i haven't gotten in yet!!!

**Comment by nileshmali** [comment] 2016-01-11 11:07
@ceolter Is this candidate for v3?

**Comment by ceolter** [comment] 2016-01-11 12:24
@nileshmali nope
v3 is all about pinned columns (left and right) and multi level groups in the headers

**Closed** 2016-01-18 21:52 UTC

**Comment by ocombe** [comment] 2016-01-18 21:55
Wooohoo is this what I think it is ?

**Comment by ceolter** [comment] 2016-01-18 21:55
this is now done, will be in the next release. if you double click the column header 'resize' bar, it will calculated the perfect width for the column.

@greglockwood i've decided to just resize the row data, not the header data, just doing the row data cells is enough to be better than the other grids.

**Comment by ceolter** [comment] 2016-01-18 21:56
@ocombe yup!!!! i'll relese in the next few days. it works pretty dam good!!! i was banging my head for about 30min coming up with designs, then wallah, it an idea sprung to my head that works!!!

**Comment by ocombe** [comment] 2016-01-18 21:57
Nice, can you call it programmatically as well (without having to tell the user to double click the resize bar)? (For example call it once you've loaded the cells)

**Comment by ceolter** [comment] 2016-01-18 21:58
yes. i put in two api methods, one takes one column, the other a list of columns.

**Comment by ocombe** [comment] 2016-01-18 21:59
That's perfect, I'll put it on the todo list for our app at work :)

**Comment by ceolter** [comment] 2016-01-18 22:05
@ocombe  welcome!

**Comment by mpetkov** [comment] 2016-03-23 18:06
So has the "Fit Contents" option been added? If so, where can I get the documentation on how to use it and what version is it available in?

**Comment by ceolter** [comment] 2016-03-23 22:46
@mpetkov 
https://www.ag-grid.com/change-log/changeLogIndex.php
3.1.0
Major: Implemented auto-size for column. Now columns can be told to fit their content.

**Comment by outofgamut** [comment] 2016-04-12 13:31
Have you considered default autosizing to the Column headers if they are larger than the cell contents? For example, with the current autosize function, if I have a long column name and the column just has an icon in it, the name of the column is truncated.

**Comment by ceolter** [comment] 2016-04-14 09:02
```Have you considered default autosizing to the Column headers if they are larger than the cell contents? ```
-> yes, it's no my list.

**Comment by smwbis** [comment] 2016-04-14 19:02
When you implement taking into account header for auto-size, would you consider doing it as an optional parameter in the api? 

`columnApi.autoSizeColumns(columns, includeHeadersBoolean)`

There are times where it's nice to hide long column names to display more data. It would be nice to have the option to include or ignore headers when determining the size.

**Comment by OzoTek** [comment] 2017-12-08 15:13
@ceolter Hi, sorry to bump up this thread but I can't seem to find if it has been implemented or not ? (Fit to the header's title in case its content is larger)
