### ISSUE TITLE
ag-grid - Cell Rendered column losing data content? when the row is dragged beyond grid and returned.

### ISSUE THREAD

**Issue by bradleykins** [ceolter/ag-grid#965] opened 2016-06-14 10:21 UTC
I tried to create a plunker but unfortunately as a newbie to web dev i have not managed to get it to display, anyone can correct this would be awesome, it should hopefully show the issue.

https://plnkr.co/edit/VWEN55cimlbxamzxxgC2

I have created a video to show this issue however:

https://sendvid.com/9apick7a

The plunker code should explain most of the bother, but our ag-grid use is with ag1 and whilst the code doesn't reflect exactly whats happening, an api call gets the data and we style it from the returned objects, its fairly representative.

As you can see the page must be refreshed (grid must be refreshed) after the column is moved outside of the grid.

Moving inside the grid is fine but if they make a mistake it ruins the content.

If this is a duplicate please let me know!

I searched but couldn't find it.

**Comment by ceolter** [comment] 2016-06-14 11:48
don't think it's a duplicate, not heard of it before. however i have no idea why this could be happening. i really need to see it a plunker or similar to troubleshoot. nobody else has reported it. are you using your own cellRenderer? if so, does it happen without a cellRenderer?

**Comment by bradleykins** [comment] 2016-06-14 12:32
no this does not happen if no cellrenderer is involved, it only happens on cellrenderer cells and i have checked my app, its happening on every single one of about 15 different grids, to all cellrenderer cells.

Can you see the code on the plunker above? if so its that code, which we are using with 4.2.5 of ag-grid we are using angular to do the site (im a bit of a newb to ag-grid / angular don't know if this would impact on this).

All i know is that if i have a cellrenderer in a cell and drag the cell away from the grid it flips out on its return (whilst being dragged)

I tried to replicate on your examples, but my guess is you excellent coding is avoiding this?

When we init the page we run an api call to a c# app that provides objects in response, these are then set to the row data:

vm.gridOptions.api.setRowData(response.data);

and everythings works fine, except this :sa: 

Anything else i can do?

**Comment by bradleykins** [comment] 2016-06-14 14:22
Apologies i believed we were on 4.2.5 but it is actually 4.1.5 - though this matters little as I made a plunker (stole the setup from another issue) and popped it together (its a bit mince and not sensible but its also not showing the issue).

New Plunker: [https://plnkr.co/edit/VWEN55cimlbxamzxxgC2?p=preview](url)

Could there be a difference between the way we display the grid and the way the example does, that cause this?

(i cannot get our method to display in plunker - again as a web dev newb i am not helping make this clearer!)

ie.

Ours
`<div ag-grid="gridOptions" style="height:800px;" class="ag-fresh" >ag-grid tag</div> `

Example
`<div id="myGrid" style="height:800px;" class="ag-fresh">ID</div>`

We are implementing quite a few other libraries as well, but i don't see making a plunker with ALL of them being possible :/


> "modernizr": "^3.3.1",
    "jquery": "^2.2.0",
    "signalr": "^2.2.0",
    "lodash": "^4.3.0",
    "angular": "^1.5.0",
    "angular-route": "^1.5.0",
    "angular-animate": "^1.5.0",
    "angular-cookies": "^1.5.0",
    "angular-sanitize": "^1.5.0",
    "angular-bootstrap": "^1.2.0",
    "angular-toastr": "^1.7.0",
    "angular-moment": "^0.10.3",
    "ng-file-upload": "^12.0.1",
    "ui-select": "angular-ui-select#^0.14.8",
    "angular-ya-treeview": "^0.2.2",
    "ag-grid": "^4.1.5",
    "ngstorage": "ng-storage#^0.4.2",
    "ng-idle": "^1.2.2",
    "angular-translate": "^2.9.0",
    "angular-ui-codemirror": "^0.3.0",
    "console-shim": "*",
    "angular-signalr-hub": "^1.6.0",
    "codemirror": "^5.12.0",
    "angular-formly": "^8.0.4",
    "api-check": "^7.5.5",
    "magic": "^1.1.0",
    "angular-formly-templates-bootstrap": "^6.3.2",
    "js-beautify": "^1.6.2",
    "repaintless": "^1.4.0",
    "angular-bootstrap-simple-chat": "^0.4.0",
    "font-awesome": "^4.6.1",
    "ngprogress": "^1.1.3"

Any thoughts?

Also the column header is displaying an icon when dragged on the plunker but we have no such icons appearing in our code? Thoughts on that?

**Comment by ceolter** [comment] 2016-06-15 09:00
none of the info above shines any light on it for me :(

i really need to see a plunker or similar to observe what is happening - so you appreciate - i get about 20 'please help' requests a day - i can't spend more than a few min on each other, otherwise i get no work of my own done :(

**Comment by bradleykins** [comment] 2016-06-15 09:17
NP Thanks, for having a look, we have decided to use a workaround of disabling only the columns with cellrenderers as this seems quite difficult to provide an adequate example for.

If i can in my own time put something together i will, but so far i can't reproduce the issue, so its obviously not a big issue as its only affected us so far (that we know of).

I appreciate the time you did look into it, though it is some form of bug its not a major issue atm.

Will update if i get a working example on a plunker.

Regards,

Nik

**Comment by ceolter** [comment] 2016-06-15 10:41
for what it's worth, it sounds like something odd in the cellRenderer - either something you are doing, or an assumption you are making and the grid is doing something . . . . but having looked at your cellRenderer, it looks pretty straight forward. it's the type of thing that if i got my hands on it, i could just inspect the dom and follow through the javascript and it would be pretty easy to see what's going on. the other option is you debug through it yourself!

as i can't reproduce, am closing the issue. can reopen if you can reproduce or otherwise identify what's wrong.

**Closed by ceolter** 2016-06-15 10:41 UTC
