### ISSUE TITLE
Rendering problem with sticky total rows

### ISSUE THREAD

**Issue by tschulte** [ceolter/ag-grid#9316] opened 2024-12-02 12:40 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

We are customers of AG Grid but at least I don't have access to Zendesk yet.

**Current behavior**

* go to https://www.ag-grid.com/javascript-data-grid/total-rows/#suppress-sticky-total-rows
* enlarge all columns significantly so that a horizontal scrollbar is showing and the needed width is maybe double the displayed width
* use the vertical scrollbar to navigate to the bottom of the table (no `.ag-sticky-bottom:not(.ag-hidden)`)
![2024-12-02-133602_1008x472_scrot](https://github.com/user-attachments/assets/9ba6b4e9-3083-467d-a77a-81fe655278dd)
* use the horizontal scrollbar
* the total rows are correctly aligned
![2024-12-02-133618_992x463_scrot](https://github.com/user-attachments/assets/24a16d0d-8774-485a-8cd0-a1a024867423)
* use the vertical scrollbar and navigate anywhere but the bottom of the table (some `.ag-sticky-bottom:not(.ag-hidden)`)
* the sticky rows are not horizontally aligned
![2024-12-02-133633_995x466_scrot](https://github.com/user-attachments/assets/a6f99d0a-abbb-4d3b-9271-47e21426fc30)
* When you now use the horizontal scrollbar again, the sticky rows repair themselves.
![2024-12-02-133911_989x462_scrot](https://github.com/user-attachments/assets/25e5f4d2-ae71-4cc5-9da6-3092e77bdaf5)

This issue seems not to be with .ag-sticky-top rows.

**Expected behavior**

The sticky bottom is always correctly aligned.

**Please tell us about your environment:**
Windows 10, Windows 11, Linux

* **AG Grid version:** 32.3.3

* **Browser:**
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

"Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Whatever you use for https://www.ag-grid.com/javascript-data-grid/total-rows/#suppress-sticky-total-rows

**Comment by AG-Zoheil** [comment] 2024-12-24 11:56
Hi @tschulte,

Thanks for getting in touch.

We've been unable to reproduce this in our latest production example to the page you've linked.
I've forked a plunker of it here: https://plnkr.co/edit/a3WIUlnpk8vx3onJ?open=main.js.

I'll close this issue and encourage you to contact us via ZenDesk if your access has been sorted by now as that is the quickest and most efficient support route for enterprise users.

Alternatively, feel free to reply here if you are still unable to access your ZenDesk.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-12-24 11:56 UTC
