### ISSUE TITLE
Ng-click fires more than once using ag-grid v5.0 

### ISSUE THREAD

**Issue by smelyakov** [ceolter/ag-grid#1031] opened 2016-07-21 11:54 UTC
Hi,

I'm using custom cell templates and renderers with ng-click directive attached.
Everything works fine with ag-grid 4.x, but with v5.x ng-click callback fires several times.

Please, take look on the plunk https://plnkr.co/edit/pqTTACOqkBk8E2tCUDpj?p=preview.
Try to drag a column and then click on any 'Click me..' text

**Comment by saifeer** [comment] 2016-07-22 00:14
I am facing this issue as well.

@ceolter, Can you please check this issue as it seems like a big problem when using Angular+Ag-grid. 

You wouldn't even need a plunkr for it, you can just reproduce it on the ag-grid website: https://www.ag-grid.com/best-angularjs-data-grid/index.php

Just go down to the Angular compiling section and when you click on the button in the "Age" field, it fires just once but now just reorder the columns and then click again and you will find it firing multiple times.

Very strange that no one picked up this issue till now...

Seems to me that the angular1Compile() function is called since the displayColumnsChanged event is fired. This recompiles the row DOM but AngularJS doesn't like once recompiled DOM to be recompiled again as it duplicates the bindings.

Thanks
S

**Comment by dhiegoatencio** [comment] 2016-07-22 20:44
I suggest you to remove angular from your cells, i did it in my work and now everything is running better. Your application will get a performance upgrade. In my opinion, angular is good for Form's and control of application, but for grid data, angular is not so good.

I suggest you to avoid angular.compile in your grid and try to implement your cells using cellRenderer.

**Comment by saifeer** [comment] 2016-07-23 14:35
I do not agree with this. There is a property "angularCompileRows" that can be defined to true on the grid which essentially breaks the whole grid as soon as you as much as try resizing the columns. The solution cannot be to not use Angular. If that's the case, why keep a property that would break the grid in the first place only to be told to not use it!

There could be many scenarios where you need a grid inside of an angular application and you need angular to be able to talk to the contents of the grid and vice versa. I would assume Niall saw some use-cases or demand for angular support for him to actually allow angular compilation. 

Thanks
S

**Comment by ceolter** [comment] 2016-07-29 10:51
this is already fixed and released in latest.

sorry for delay, i didn't realise this post was here. was also reported on the paid forum (which i gave priority to as soon as i got back).

**Closed by ceolter** 2016-07-29 10:51 UTC
