### ISSUE TITLE
After sort/filter, selected row(s) aren't cleared

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/ag-grid#396] opened 2015-08-25 23:47 UTC
If you have a row selected and then sort or filter, the row remains selected (although it may not be the same row anymore).

Row selection should be cleared on sort or filter.

Cell focus is already cleared.

**Comment by ceolter** [comment] 2015-08-26 11:42
can't reproduce. on the test drive, i selected 'Olivia Brennan', and then sorted and filtered on the name column. Olivia Brennan remained selected regardless of the sort of filter.

**Comment by scotthovestadt** [comment] 2015-08-26 13:39
@ceolter OK, but I think the behavior is bugged with a Datasource + Infinite scrolling. I think it keeps the row selected even if it isn't the same row.

I can have custom code de-select the row, but it seems like it should be de-selected automatically when a datasource is used.

I am using datasource+ infinite scrolling with millions of rows.

**Comment by ceolter** [comment] 2015-08-26 20:58
Ah, you didn't mention you were using infinite scrolling, I didn't test with that. I'll take another look (not now, but reopening the issue).

**Comment by TFrascaroli** [comment] 2015-10-06 09:43
It does happen (test it here: http://www.ag-grid.com/angular-grid-virtual-paging/virtualPagingServerSide.html)
If deselection after sort / filter is the course of action let me know and I'll try to stitch a PR together.

**Comment by randdusing** [comment] 2016-10-21 22:03
On https://www.ag-grid.com/example.php: If I select Sophie Beckham, filter out Country by Ireland, and then remove the filter, Sophie Beckham stays selected. Is that intended?

**Comment by ceolter** [comment] 2016-10-31 14:05
@TFrascaroli that link is an old link, we don't have 'angular' in our URL's anymore. this is the correct one, that you should be getting from our documentation:
https://www.ag-grid.com/javascript-grid-virtual-paging/virtualPagingServerSide.html

**Comment by ceolter** [comment] 2016-10-31 14:06
the original issue, selection with infinite scrolling, is fixed in latest, so closing.

**Comment by ceolter** [comment] 2016-10-31 14:06
@randdusing ```If I select Sophie Beckham, filter out Country by Ireland, and then remove the filter, Sophie Beckham stays selected. Is that intended?```
=> yes, that's intended. selection and filtering are not related.

**Closed by ceolter** 2016-10-31 14:06 UTC
