### ISSUE TITLE
Allow standard browser selection mode (for copy/paste)

### ISSUE THREAD

**Issue by kbdguy** [ceolter/ag-grid#87] opened 2015-04-23 19:36 UTC
I will frequently browse a grid, and see something I want to copy (for a subsequent "paste" into another application) in a cell or maybe multiple cells.  Seems like that's not supported in this grid: I can't select anything for copy/paste. If I'm right, then I'd like to make a request to get that functionality added somehow!

**Comment by ceolter** [comment] 2015-04-23 19:45
yes your right, that's not supported, and yes your right, that would be
cool. thanks for putting it onto the list. i guess we should have 'user
selects cells', and then ctrl+c to copy the selection into the clipboard as
csv or similar.

On 23 April 2015 at 20:36, kbdguy <notifications@github.com> wrote:

> I will frequently browse a grid, and see something I want to copy (for a
> subsequent "paste" into another application) in a cell or maybe multiple
> cells. Seems like that's not supported in this grid: I can't select
> anything for copy/paste. If I'm right, then I'd like to make a request to
> get that functionality added somehow!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/87>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by okonovalenko** [comment] 2015-07-02 12:37
Is this functionality available yet?

**Comment by ceolter** [comment] 2015-07-02 14:29
nope, sorry.

**Comment by pillaiv** [comment] 2015-07-07 13:05
Is it possible to copy multiple rows from excel and paste into the grid ?

**Comment by ceolter** [comment] 2015-07-07 19:26
> Is it possible to copy multiple rows from excel and paste into the grid ?

no, afraid not.

**Comment by okonovalenko** [comment] 2015-08-13 14:50
CTRL+C one cell at least would be a killer feature, waiting patiently :)

**Comment by ceolter** [comment] 2015-08-13 15:51
:) yea, i hear yea, it's on my list, honest, just so busy, eg i've just finished implementing 'master / slave' grids, which allows grid footers!!!

**Comment by RemiAWE** [comment] 2015-08-28 09:54
It seems to be caused by the property `-webkit-user-select: none;` on the class `ag-root`. Why do you use this property ?

**Comment by ceolter** [comment] 2015-08-28 10:10
to make the grid behave more like a grid. if your in excel, for example, it's not normal to select text in the cell, but cells as a whole. my plan is in the future, to allow cell selection. and then ctrl+c to copy those cells. for now, the plan is to get ctrl+c to copy the selected rows.

**Comment by rajal2** [comment] 2015-09-03 07:55
eagerly waiting for this copy/paste feature!

**Comment by sarinderv** [comment] 2015-10-07 18:43
+1 for this feature

**Comment by ebbflowgo** [comment] 2015-11-02 14:17
+1 for this feature

**Comment by byunru** [comment] 2015-11-18 23:42
+1 for this feature

**Comment by mafalarz** [comment] 2015-11-20 14:37
Just wanted to mention that ag-grid was very interesting to us, but missing feature was a deal breaker for our company adopting ag-grid

**Comment by ceolter** [comment] 2015-11-21 08:28
I can't win them all. Give me a few months early next year, all the standard grid features will be in.

**Comment by spacem** [comment] 2015-12-07 10:09
small hack to get this mostly working through css - may cause other problems
div.ag-root {
  -webkit-user-select:text;
	-moz-user-select:text;
	-ms-user-select:text;
	user-select:text;
}

**Comment by sarinderv** [comment] 2015-12-08 16:33
The hack does enable copy from individual cells, like http://ui-grid.info
However, paste does not format correctly (tried with Windows - FF, Chrome, IE). Ideally, it should have 'user selects cells' and then paste the selection into the clipboard as CSV or similar.

**Comment by YULPontifex** [comment] 2016-01-27 06:10
+1 for this feature

**Comment by PierrePIRONIN** [comment] 2016-02-18 11:37
+1

**Comment by Roriz** [comment] 2016-04-06 14:03
+1 for this feature

**Comment by ceolter** [comment] 2016-04-14 08:11
this is implemented in v4 of ag-Grid Enterprise. you range select (or select rows) and can copy to clipboard.

**Closed by ceolter** 2016-04-14 08:11 UTC

**Comment by openseah** [comment] 2016-11-03 08:51
CTRL+C one cell still not available, i don't why using -webkit-user-select: none.
I think CTRL+C one cell should be basic function like other grid.

**Comment by ceolter** [comment] 2016-11-07 14:16
@openseah yes it is, go here:
https://www.ag-grid.com/example.php
select a cell, ctrl+c, that cell gets copied

**Comment by gsawasthi25** [comment] 2016-11-22 07:07
CTRL+C only works when rowModelType is standard.

How to make it work if we are using viewport ?

**Comment by ceolter** [comment] 2016-12-02 16:52
```CTRL+C only works when rowModelType is standard.``` not true. it works with viewport. eg it's working on the example here: https://www.ag-grid.com/javascript-grid-viewport/

**Comment by pdavin** [comment] 2017-01-21 00:20
This doesn't work if you have suppressCellSelection on. We don't want the web grid to behave like Excel, so that's why we have that turned on. Standard browser selection mode would have a text cursor when the mouse is over text (not a pointer), and the cursor would select text (ie, you could select part of a word or sentence within a cell, rather than just the whole cell). Any chance we could get standard browser selection capabilities when suppressCellSelection is on? 

Here are my full grid options (excluding columnsDefs + rowData): 
      enableSorting: true,
      suppressCellSelection: true,
      suppressContextMenu: true,
      suppressMenuFilterPanel: true,
      suppressMenuMainPanel: true,
      suppressMenuColumnPanel: true,
      suppressRowClickSelection: true

**Comment by prinks17** [comment] 2017-04-06 13:26
Is the copy cell data(through Control +C ) feature available only for Enterprise edition of Ag-grid?

**Comment by a497988** [comment] 2017-06-14 17:03
Is there a way to select only certain text in a cell and copy?

**Comment by fantasybei** [comment] 2017-06-29 05:47
have the same question as @a497988 mentioned

**Comment by jkjha** [comment] 2017-08-08 08:28
Very disappointed to know one of the required feature is Enterprise only feature.
 In this case, user like me need to be cautious before simply using ag-grid (assuming its free).

**Comment by EmileIndik** [comment] 2017-10-31 00:07
Do you know if the workaround @spacem gave breaks any functionality?

**Comment by Mage111** [comment] 2017-11-07 13:44
same question.
just want to select and copy text from the grid

**Comment by avshyz** [comment] 2017-12-19 15:12
+1 for this feature.

**Comment by Mage111** [comment] 2017-12-20 07:00
just change the default css solved the problem.
`-webkit-user-select:text;
-moz-user-select:text;
-ms-user-select:text;
user-select:text;`

**Comment by nite** [comment] 2018-02-15 13:52
I've created a gist/directive that seems the closest to the best of both worlds for me 
https://gist.github.com/nite/dea82d184411a51fc6bc6adc7edaa422
- essentially you can have cell selection mode, so you can copy to clipboard on a cell or range of cells selection, but cell selection will also highlight a row (eg. if you have contextual actions on a row, then this is a better UX)

**Comment by Lazarencjusz** [comment] 2018-05-21 11:53
@Mage111 it solvs just selection problem, still you are not able copy selected text by `ctrl + c`, however RMP menu copy works.

**Comment by jianghan200** [comment] 2018-10-23 09:01
> just change the default css solved the problem.
> `-webkit-user-select:text; -moz-user-select:text; -ms-user-select:text; user-select:text;`

In this way, all the data are stick together without blank or tab, how to solved this?

**Comment by quyho-tnc** [comment] 2019-04-17 09:05
create new class and apply this css
` {
-webkit-user-select:text;
-moz-user-select:text;
-ms-user-select:text;
user-select:text;
}`
after combine with cellRendererFramework to use this className for that cell

**Comment by gportela85** [comment] 2019-04-17 10:24
see: https://www.ag-grid.com/javascript-grid-properties/ - `enableCellTextSelection`

**Comment by kbdguy** [comment] 2019-04-17 12:57
I believe enableCellTextSelection is limited to "enterprise" edition, so other work-arounds are valuable.

**Comment by gportela85** [comment] 2019-04-18 16:40
@kbdguy The enableCellTextSelection is applied directly to the cell and should work with community version.

**Comment by kbdguy** [comment] 2019-04-18 22:20
@gportela85 Thanks!  I don't understand what you mean by "applied directly to the cell." In Community edition, the attribute is not available as a member of the ColDef interface or the GridOptions interface or GridOptions.api or GridOptions.columnApi.  Or is this something new? I'm using version 20.

**Comment by gportela85** [comment] 2019-04-19 13:09
@kbdguy It was introduced in 20.1.

**Comment by petersg83** [comment] 2019-09-11 13:57
Add `enableCellTextSelection: true` in the gridOptions

**Comment by Cinema180** [comment] 2019-09-30 11:31
There seems to be a bug when using `enableCellTextSelection: true` in my project's grid (community edition). Double-clicking on a cell causes the highlighted selection to bleed over into other cells. I have been able to reproduce this behaviour in the example grid at https://www.ag-grid.com/javascript-grid-clipboard/#using-enablecelltextselection (you first need to set `defaultColDef: { editable: false }` in Plunker), as can be seen in this screenshot where I double-clicked on a Country column cell:

![image](https://user-images.githubusercontent.com/45290956/65874234-31f3f700-e37d-11e9-8730-168a42bf95c0.png)

Any plans to fix this?

**Comment by kanine** [comment] 2020-03-06 10:03
When you set enableCellTextSelection to true it causes numeric alignments to shift to the left.

ie those with type: "numericColumn"

Community Edition.

**Comment by AllaSorokina** [comment] 2020-09-16 18:28
We have "enableCellTextSelection" set to true, it works on Chrome fine, but doesn't do anything on Safari.
Any advice how to solve it for Sarari?

**Comment by chamikara1998** [comment] 2021-02-19 08:03
Add this to your stylesheet
.ag-root{
    -webkit-user-select: auto !important;
}

**Comment by misaunde** [comment] 2021-04-12 22:11
I want to be able to select a row if I click on it and copy data from the cell I clicked on. Is this possible?
For example:
````
suppressRowClickSelection: false,
rowSelection: 'single',
onSelectionChanged: onSelect,
enableCellTextSelection: true
````

suppressRowClickSelection appears to change the copy/paste behavior to copy the entire row instead of just the cell I was at.

**Comment by mohammedRaiyan** [comment] 2021-08-08 01:15
Hi ... Is it possible to over ride the default copy,paset and select all options in the browser when user selects a text pop then a custom copy paste options

**Comment by mohammedRaiyan** [comment] 2021-08-08 01:16
![Uploading Screenshot_2021-08-07-19-20-52-076_com.android.chrome.jpg…]()
`

It is possible to change the copy paste options

**Comment by deepikagupta31** [comment] 2024-04-05 01:55
Is there any feature to enableCellTextSelection only for a particular row?
