### ISSUE TITLE
4.2.X Small bug list, major features

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#931] opened 2016-05-27 20:20 UTC
*I do use the enterprise version, and have no idea how to buy it. Please help [here](https://www.ag-grid.com/forum/showthread.php?tid=3775)

This list contains things I notice in the 4.2.X:
- Grouping / Ungrouping is now slow. I have a 60K rows table, and grouping was very fast before.
   - Example: https://www.ag-grid.com/example.php , use 100K rows.
- Select All (maybe deselect as well, I wouldnt know) does not finish (on a 60K rows table). Instead, it crashes the browser tab.
    - After some more testing, it sometimes happen on smaller tables (300 rows) too. constantly adding memory, and huge CPU usage. (1200% Memory usage)
        - 300 rows finish, but takes a few minutes
- Tables are crashing the browser - Don't know why, but the tables are gradually taking more memory, and CPU usage, to a point where the tab crashes - https://ag-grid.com/ag-grid-tutorials/index.php
- Open/Close group is now really slow
    - Example: https://www.ag-grid.com/example.php , use 100K rows.
- When a row is selected, right click any cell, copy, copies the selected row
- Filtering - impossible to filter "equals ''" (empty string, removes filter)
- Filtering '=== null' values is allowed by just writing (as text) null
- Sorting large tables is slow
- Grouping icon is covering the entire screen, 
    - Add .ag-fresh img {width:16px;} 
    -Using new bootstrap theme, no online example
- New selectbox does not seem to have an option to revert to old one - I think it would be better to use a normal checkbox, or an image url. (As far as I know, saves only one copy in memory)

I have so many crashes, the above testing took 20 minutes, and I believe there are more bugs, but they are maybe derived from these.

Hope that helps,
And although there are some bugs fixed in the new 4.2.X, that I really like, I am reverting to the more stable version:
- "ag-grid": "4.1.5",
- "ag-grid-enterprise": "4.1.4",

**Comment by ceolter** [comment] 2016-05-28 09:44
noted. thanks. i'll look into the performance, that's worrying.

**Comment by ceolter** [comment] 2016-05-28 09:44
regards buying a license, email accounts@ag-grid.com

**Comment by ceolter** [comment] 2016-06-01 08:33
"Grouping / Ungrouping is now slow. I have a 60K rows table, and grouping was very fast before."
-> the test is now aggregating all the month columns, before it was just aggregating two of the columns. this is the cause of the slowness. in the next release i'll bring it back to just aggregating two rows.

**Comment by ceolter** [comment] 2016-06-01 08:55
i cannot reproduce any of the other items above. for me:
+ sorting works as fast as it used to
+ open / close group is not slow
+ selection is not slow (if you group, then select a group, it selects the whole group very fast)
+ "When a row is selected, right click any cell, copy, copies the selected row" -> this hasn't changed and is the intention, this is what the docs say will happen.
+ "Grouping icon is covering the entire screen" -> not for me
+ "Tables are crashing the browser " -> again i don't experience this
+ "New selectbox does not seem to have an option to revert to old one - I think it would be better to use a normal checkbox, or an image url. (As far as I know, saves only one copy in memory)" -> it's now in line with the other icons in the system. it is easy to change this to another image.

with all the items i cannot reproduce, i'm wondering if your browser is caching something it shouldn't???

as this issue is pretty much items i can't reproduce, i'm closing.

**Closed by ceolter** 2016-06-01 08:55 UTC

**Comment by AmitMY** [comment] 2016-06-01 11:28
Ill try to add an example soon. For the grouping, I have no aggregation and still it is very heavy.
Ill look into it more. Your table is the best table I have ever encountered, its worth the time :)
