### ISSUE TITLE
onFillStart fired when the mouse released not with starting dragging

### ISSUE THREAD

**Issue by MoatazAbdallh** [ceolter/ag-grid#9453] opened 2024-12-10 12:51 UTC
**I'm submitting a ...**  
```
[x] bug report
```

**Requesting Community Support**

**Providing a Reproducible Scenario**
In the below example, i added onFillStart to detect when it will be fired it seems that the callback function called after the mouse released, not during start dragging, which is the same behavior as onFillEnd
Reproducible Link: https://codesandbox.io/p/sandbox/fill-handle-forked-hvgzyl?file=%2Fsrc%2Findex.tsx%3A78%2C11-78%2C22

**Please tell us about your environment:**
Operating system: MacOS and Windows

* **AG Grid version:** ^32.3.3

* **Browser:**
All Browsers

* **Language:** JS

**Comment by AG-Zoheil** [comment] 2024-12-24 11:42
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-13774**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Closed as completed by AG-Zoheil** 2024-12-24 11:42 UTC
Labels: invalid

**Comment by AG-Zoheil** [comment] 2025-01-28 10:22
Hi,

Please note that we've reviewed this item and can provide an update:

This is not a bug but expected behaviour - see here: https://www.ag-grid.com/javascript-data-grid/cell-selection-fill-handle/#fill-handle-events

If you'd like to capture when dragging started please use: `onDragStarted`

Kind regards,
Zoheil
