### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by ainulhaqkhan** [ceolter/ag-grid#6610] opened 2023-05-17 08:00 UTC
faced the issue in react js application when using ag-grid-react

 **ResizeObserver loop limit exceeded**

**Comment by StephenCooper** [comment] 2023-05-17 08:37
Duplicate of https://github.com/ag-grid/ag-grid/issues/6562

**Closed as completed by StephenCooper** 2023-05-17 08:37 UTC
