### ISSUE TITLE
cellRenderer not detecting prop changes

### ISSUE THREAD

**Issue by greygatch** [ceolter/ag-grid#4858] opened 2022-01-04 17:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Grid team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunkr, from any example in our website use the plunkr button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

Props not updating within ag-grid cellRenderer.

**Expected behavior**

I should be able to pass updated props to the ag-grid cellRenderer.

**Please tell us about your environment:**

MacOS, VSCode, npm, etc.

* **AG Grid version:** 26.x

* **Browser:**

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Props/arguments passed to the cellRenderer are not updated. Setting and passing state in cellRendererParams, doesn't change the data. It appears as if the props are cached the first time the function is run.

This appears similar to [this](https://github.com/ag-grid/ag-grid/issues/4348) issue, but it looks like it was closed because it was ignored for a while.

The workarounds mentioned (item getter being passed in cellRendererParams) do not work for me, and I'm forced to mutate the row data directly, and then redrawing the cells.

**Comment by Cacique99** [comment] 2022-01-10 14:40
Hello, I've also been experiencing the same exact issue. I think this its very crucial to have a fix for this since it goes against the foundation of React's stateful rendering and disrupts the capabilities of the component. Thank you!

**Comment by makinggoodsoftware** [comment] 2022-02-17 10:33
Hi,

 

This ticket has been flagged as managed-by-community/waiting-for-repro for a while now and there has not been any activity, to help us tidy up we are going to close it.

 

Thanks

**Closed as completed by makinggoodsoftware** 2022-02-17 10:33 UTC
Labels: waiting-for-repro

**Comment by eliaharris** [comment] 2022-07-15 14:03
For anyone who stumbles on this... As mentioned above, you need to store the data in `useRef()`

You can't pass a callback that returns `useState` variables because the callback is returning a stale object from previous states. 

When `useState` changes, a brand new object is returned. However, the callback passed into `cellRendererParams` would still be referencing the old object. If you were re-creating the callback and passing it back to AgGrid on every update, then your problem would be solved. However, a better approach is to store the data in a `useRef` and update the ref every time react updates.

For example, you can do something like this in your component.

```ts

const [data, setData] = useState<any>()

// Store a reference to it every time react updates (could also do a useEffect hook)
const dataRef = useRef<any>()
dataRef.current = data

```

Now you can simply return the reference in your cellRendererParams like so:

```ts
    cellRendererParams: {
                getDate: () => dataRef.current
    }
```

**Comment by AuthorOfTheSurf** [comment] 2024-02-02 13:40
In my case I had to try all sorts of combinations of suggestions to get what I was after. In my case, it's not the `data` that will change, I simply want my `cellRenderer` to respect a certain boolean variable:

This is a client-side React component, all it's doing is displaying an `<AgGridReact ... />`
```ts
// Create ref for our grid, because we'll need to manually re-render the rows
const gridRef = useRef<any>();

// This is the main variable that I want the cellRenderer to respect
// There is a count number, and I want to allow the user to hide it because it's a little distracting
const [hideGradeFieldCount] = useState(true);

// Create another ref that will always hold the current value of the stateful hideGradeFieldCount variable
// If you are unfamiliar with useRef, and why it is sometimes used in React, now is the time to look it up!
const hideCount = useRef<any>();
hideCount.current = hideGradeFieldCount;

// This is my cell renderer
// `value` is a standard prop
// `getHideCount` is an additional prop that I am making available to the cell renderer
function countAndAttributesRenderer(props: {
  value: string;
  getHideCount: () => boolean;
}) {
  const [count, ...attributeGradeScores] = props.value.split(" ");
  const attributes = attributeGradeScores.map(gradeScoreToGrade);

  // Notice the call to props.getHideCount()
  // If you're reading this right now, you might have expected plain old `!hideGradeFieldCount` to work,
  // but it doesn't due to the whole copying-in-parameters design of ag-grid
  return (
    <>
      <div className="flex flex-row h-full">
        {attributes.map((grade, index) => (
          <GradeChip
            key={grade + index}
            grade={grade}
            className="mr-1 my-auto"
          />
        ))}
        {!props.getHideCount() && <span>({count})</span>}
      </div>
    </>
  );
}

// In my case I must manually redraw the rows. This is because my `data` is unchanged,
// so `refreshCells()` will do nothing due to ag-grid seeing that the data for the cell is the same.
// redrawRows() is therefore required to get the cellRenderer to fire off again
useEffect(() => {
    if (gridRef.current.api) {
      gridRef.current.api.redrawRows();
    }
  }, [hideGradeFieldCount]);

// Final piece where it all comes together
return (
  <div className={`${agTheme} h-[calc(100vh-64px-64px)] m-8`}>
    <AgGridReact
      ref={gridRef}
      rowData={rowData}
      columnDefs={colDefs as any[]}
      gridOptions={{
        defaultColDef: {

          // In my case, I want to use this cellRenderer by default, so I placed it here
          // Otherwise it would just be in a particular column(s) columnDef
          cellRenderer: countAndAttributesRenderer,

          // I place cellRendererParams right next to it
          // This `getHideCount` getter gets added to the `props` of `countAndAttributesRenderer` ^^
          cellRendererParams: {
            getHideCount: () => hideCount.current,
          },

          resizable: true,
        },
      }}
    />
  </div>
);
```

Looks like 5-6 steps to get the stateful boolean value to be respected, but it works. I am sure there must be a way to simplify this, but I genuinely tried all sorts of combinations for over an hour and I need to move on

It's only my first week using ag-grid and I really like it! Thank you to the team for putting it together and I have had a great experience with it so far. It allows me to just build build build and the simple data + columnDef + gridOptions design and the built-in themes are so nice. It makes so many common tasks like sorting, filtering, and freezing columns totally easy.

Still some learning pains of course, but that's normal. Hope this comment helps some people :)

**Comment by Nikoobox** [comment] 2025-02-21 19:37
why is this closed?

**Comment by AG-Zoheil** [comment] 2025-02-24 09:05
Hi @Nikoobox,

Thank you for your comment.

As you can see this is quite an old issue from **more than three years ago**.

The grid has naturally advanced a lot since then. If you are still having problems and think there is a bug, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team investigate this in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
