### ISSUE TITLE
navigateToNextCell not looking in floatingRows

### ISSUE THREAD

**Issue by maraisr** [ceolter/ag-grid#703] opened 2016-02-09 02:49 UTC
When you `navigateToNextCell` giving a key of 37, rowIndex of 0, and a valid column, you'd expect it to move back a field. But when you call this function on a floatingCellRenderer closure, using `params.api.rowRenderer.navigateToNextCell` nothing happens..

When I took a look at the source code, it seems to be failing at `renderedRow = this.renderedRows[cellToFocus.rowIndex];`.. I hopped into the source, and console logged the `renderedTopFloatingRows` where the `rowIndex` and `column` with its associated cell is there. 

What would be the agGrid way of approaching this? Reason for this - i'm using the floating top row as like a "insert new row" row. With editable fields, posting to my backend api, and resetting the datasource.

**Comment by ceolter** [comment] 2016-02-09 09:35
the navigation just wasn't designed to work with floating headers / footers, so it won't work.

**Comment by maraisr** [comment] 2016-02-09 11:02
Is there a way of making it work? Potentially a "hacky" way? Like i've already got the custom keydown event listeners capturing the tab key (9) and firing the `navigateToNextCell` with keycode 37 (or whatever the arrow keycodes are).. 

Is there maybe an api to get the `eGridCell` passing in a colId, and rowIndex? To manually focusing it, and running the "move to next cell" logic myself?

**Comment by ceolter** [comment] 2016-02-09 11:14
when i developed this part, i came to the conclusion it was a bit of work to get the navigation working with the floating cells. i had a quick 5min look this morning, and could see how the navigation uses rowIndex to move up and down. this is where the problem is i believe.

**Comment by maraisr** [comment] 2016-02-09 11:17
I'm not so much worried about mixing navigation between normal rows, and floating rows.. Just between cells in floating rows, and normal rows independently.

Not asking to add this feature into your codebase! haha you do alot for the community already! Just wondering if there was a way to achieve this using the current pipes.

Oh and sorry about turning this more into a "how can i do this" rather an actually an issue.. Im happy to jump to the forum if need be?

**Comment by ceolter** [comment] 2016-02-09 11:54
```
Just wondering if there was a way to achieve this using the current pipes
```
-> not that i'm aware of. sorry, i don't have the time to look into it, to do so i'd have to stop doing what i'm doing. i get about 4 large questions a day (like this one) that i would have to look into the code at parts i have forgot how they work, so would take me 30min and possibly drag into an hour, i just don't have the time to do that, sorry :(

**Comment by maraisr** [comment] 2016-02-09 22:20
No worries mate! Didn't expect you to either! As I alluded to earlier, you do an amazing job with this project already!

This grid is power Australia's largest airlines.. 

If you wish - you can mark this as closed!

**Comment by ceolter** [comment] 2016-02-10 08:43
Jesus, I'm never flying Australian Airways in that case!!! lol

Right, closing :) thanks

**Closed by ceolter** 2016-02-10 08:43 UTC
