### ISSUE TITLE
[Bug] Disappearing view

### ISSUE THREAD

**Issue by AmitMY** [ceolter/ag-grid#1461] opened 2017-02-09 18:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After reproducing like below, view disappears, and reappears only after scroll

**Minimal reproduction of the problem with instructions**
- Go to https://www.ag-grid.com/example.php
- scroll to the center of the table (vertically)
- Pin `Name` column right.
- Pin `Name` column left
Result:
![image](https://cloud.githubusercontent.com/assets/5757359/22797834/76a41d6a-ef08-11e6-96d9-082a75ea1e8e.png)

* **Browser:**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by begincalendar** [comment] 2017-02-10 01:01
Stack trace:

```
src/ts/gridPanel/gridPanel.ts:1417                                               
src/ts/gridPanel/gridPanel.ts:1315                                               
dist/lib/eventService.js:80                                                      
dist/lib/eventService.js:79                                                      
src/ts/columnController/columnController.ts:1662                                 
src/ts/columnController/columnController.ts:1555                                 
src/ts/columnController/columnController.ts:982                                  
src/ts/columnController/columnController.ts:943                                  
src/ts/columnController/columnController.ts:928                                  
                                                                                 
// I think this is the border between the free version and the enterprise        
// version, as I can't find the top-of-stack calls (below) in the public repo.   
                                                                                 
MenuItemMapper</MenuItemMapper.prototype.getStockMenuItem/<.action@https://www.ag-grid.com/dist/ag-grid-enterprise.js?ignore=notused40:26952:46
MenuItemComponent</MenuItemComponent.prototype.onOptionSelected@https://www.ag-grid.com/dist/ag-grid-enterprise.js?ignore=notused40:26867:13
```

**Comment by AmitMY** [comment] 2017-02-10 08:28
I do not see any errors, however, it is quite clear what is going on,
The scroll is in the middle, meaning that the middle part is being rendered. Then, after some manipulations, the view updates (still renders middle) and then the scroll changes, meaning that you are left to see dead space.

**Comment by begincalendar** [comment] 2017-02-10 09:36
Sorry should have clarified.

That's not an error stacktrace, just the stacktrace of the line that causes the disappearance.

**Comment by oryam** [comment] 2017-03-10 09:59
Same issue on **IE 11**. Tested on the official online demo too.
Behavior: just scroll **quickly** horizontally. New columns are rendered with a delay (1-2 sec).

**Comment by AmitMY** [comment] 2017-04-06 13:59
@seanlandsman Please add this to the pipeline, as this is a very annoying bug, with 100% reproduction rate

**Comment by seanlandsman** [comment] 2017-04-06 14:05
Hi @AmitMY 

This has now been added to the pipeline as AG-384 - I'm not sure why it wasnt before, apologies for that

**Comment by AmitMY** [comment] 2017-04-06 14:20
@seanlandsman Mass adding of stuff to the tracker, something had to fall fall between the cracks :)

**Comment by ceolter** [comment] 2017-04-11 14:41
just tested on latest, cannot reproduce. i remember fixing this a few weeks ago, so believe it to be fixed in the latest.

**Comment by AmitMY** [comment] 2017-04-11 18:26
@ceolter If by latest, you mean the same version that is on the website, but is not fixed yet.
(If you are testing an internal build, I can't confirm)

**Comment by AmitMY** [comment] 2017-04-17 08:36
@ceolter I just checked this on v9.0.3 which was released 4 days ago. Bug is still there.

**Comment by AmitMY** [comment] 2017-05-15 08:34
@ceolter @seanlandsman @makinggoodsoftware Please reopen.

**Comment by seanlandsman** [comment] 2017-05-15 09:19
@AmitMY sorry, this slipped through my radar as it was closed - I've re-opend this now

thanks

**Comment by ceolter** [comment] 2017-05-15 16:32
fixed. will be in next release.

**Comment by makinggoodsoftware** [comment] 2017-05-22 10:31
Hi,

Just to let you know that v10.0.0 has just been released and includes the fix that we discussed in this thread.

Thanks

**Closed by makinggoodsoftware** 2017-05-22 10:31 UTC
Labels: bug
