### ISSUE TITLE
[component pagination] Custom pagination panel template

### ISSUE THREAD

**Issue by EndarValuk** [ceolter/ag-grid#909] opened 2016-05-18 05:52 UTC
For now its not possible to implement custom template for "footer panel" (control marked as id="south").
Would be nice to have such feature.
Usage, e.g. reload button, export button.
![untitled](https://cloud.githubusercontent.com/assets/4099836/15348750/a69d3e6a-1ce6-11e6-932c-3068202a2dec.png)

**Comment by rsauget** [comment] 2016-06-16 11:52
+1

**Comment by anton-chernov** [comment] 2016-07-07 10:27
+1

**Comment by sasivarnan** [comment] 2016-07-12 07:08
+1

**Comment by agatsoh** [comment] 2016-10-11 18:59
+1

**Comment by adrianMaersk** [comment] 2016-10-21 09:05
+1

**Comment by chemicalbr** [comment] 2016-10-21 13:41
+1

**Comment by deepakjan** [comment] 2016-10-26 19:37
+1

**Comment by BoyceLyu** [comment] 2016-11-07 16:26
+1

**Comment by donduni** [comment] 2017-01-05 08:02
+1

**Comment by MehdiSaeedifar** [comment] 2017-01-14 16:07
+1

**Comment by naveenballa** [comment] 2017-01-16 04:58
+1

**Comment by seanlandsman** [comment] 2017-01-24 10:37
tracked by AG-126
https://www.ag-grid.com/ag-grid-pipeline/

**Comment by ceolter** [comment] 2017-01-26 09:51
duplicate of https://github.com/ceolter/ag-grid/issues/530
closing

**Closed by ceolter** 2017-01-26 09:51 UTC
Labels: enhancement

**Comment by iosifpetre18** [comment] 2018-07-05 14:33
so is there a way to do a custom pagination?

**Comment by EliGitHub1** [comment] 2019-02-06 16:05
There's actually a way to custom ag-grid pagination:

simply use( on the component js) styled component( I use react) as I show below:

const wrapper = styled.div`
.ag-paging-button {
border:none;
}
`;

**Comment by gokilagithub** [comment] 2019-10-11 09:09
> There's actually a way to custom ag-grid pagination:
> 
> simply use( on the component js) styled component( I use react) as I show below:
> 
> const wrapper = styled.div`
> 
> .ag-paging-button {
> border:none;
> }
> 
> `;

Could you please tell me where to use this..How to achieve the custom pagination.

I have attached the screens.I want to bring the page size input box in the same row of pagination.how to achieve it ?pls help
![table](https://user-images.githubusercontent.com/56433118/66639614-cccdba80-ec34-11e9-98a0-24a9311cca7c.png)

**Comment by Guima21dv** [comment] 2019-11-19 14:00
> I have attached the screens.I want to bring the page size input box in the same row of pagination.how to achieve it ?pls help

anyone know how i do this?
