### ISSUE TITLE
Set filter not working when the value wasn't in the filter selection list initially

### ISSUE THREAD

**Issue by stevey1** [ceolter/ag-grid#1582] opened 2017-04-07 20:22 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a 3 rows grid with column call status. Initially status value of 3 rows are: 'Active','Active','Closed'. So the set filter list of the column are: (They are all checked) 'Select All'(checked),'Active'(checked),'Close'(checked). Then I delete one of row with Active Status, then the filter list becomes: **'Select All'(checked)**,'Active'(checked),'Close'(checked), 'Deleted' (unchecked)
**And the delete row is displayed in the grid** 
![capture](https://cloud.githubusercontent.com/assets/4032245/24819177/caf97026-1ba0-11e7-967d-5c44157b2ea7.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4032245/24819191/d5d0cff8-1ba0-11e7-810d-5e0dcb417b4f.PNG)

**Expected behavior**

After deletion the filter list should be: **'Select All'(unchecked)**,'Active'(checked),'Close'(checked), 'Deleted' (unchecked)
**And the delete row should be filter out from the grid** 
I try the code below, which is not working. onFilterChanged seems not working as expected
`                        statusFilter.setModel(availableUniqueValues);
                        grid.api.onFilterChanged();`
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Window and IIS 7
* **ag-Grid version:** 8.2.0

* **Browser:**

Chrome
* **Language:** ES5

**Comment by seanlandsman** [comment] 2017-04-18 09:26
I'm afraid I'm not sure I follow your issue here - are you saying that deleted rows are appearing in the grid due to filtering?

If you can provide a plunker that will help us investigate further

**Comment by seanlandsman** [comment] 2017-05-04 09:44
No repro so closing - please feel free to reopen if you can provide a reproducible test case

**Closed by seanlandsman** 2017-05-04 09:44 UTC
Labels: needs_repro
