### ISSUE TITLE
innerHeaderComponent refreshable

### ISSUE THREAD

**Issue by srccircumflex** [ceolter/ag-grid#9595] opened 2024-12-20 14:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[x] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The component is only called during initialization.

**Expected behavior**
The obvious solution would be a refresh method that reacts to the setting of the column definition or a `redrawHeader` method?

**My quick fix** is to call `HeaderComp.workOutInnerHeaderComponent` inside `HeaderComp.refresh` and replace/add the node in `HeaderComp.eText`. I use the component to style the column depending on data from outside the grid. The refresh is triggered by setting the column definition again.

* **AG Grid version:** 33.0.3

**Comment by sabahang** [comment] 2024-12-20 16:12
@scotthovestadt are you facing this only on version 33.0.3 or on previous versions (before 33) as well? 
Would you be able to give us a plnkr example to reproduce the issue?

**Comment by srccircumflex** [comment] 2024-12-21 04:28
The feature is _new since v33.0.0_. I think a sample code is not necessary, I just configure the `colDef` according to the documentation of `innerHeaderComponent` and change the `headerName` at runtime.
This shows the change is not rendered (but present in the underlying grid data). The column header still shows the initial `headerName`.

**Comment by sabahang** [comment] 2024-12-23 13:29
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-13763

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

Kind regards,

**Closed as completed by sabahang** 2024-12-23 13:29 UTC
Labels: AG-13763
