### ISSUE TITLE
Column visibility issue

### ISSUE THREAD

**Issue by AbuSufyan** [ceolter/ag-grid#1160] opened 2016-09-23 12:17 UTC
Hi,

We are facing an issue with ag-grid with rows about 750 and columns are 25 where only first column draws while others remain invisible until we scroll right. Please refer snapshots explaining it further.
Please note that ag-grid is placed under Bootstrap tab and column visibility issue occurs when switching between tabs.

![firsttab](https://cloud.githubusercontent.com/assets/11941140/18785313/f8c17e34-81b0-11e6-98dd-269213b7585a.png)
![secondtab](https://cloud.githubusercontent.com/assets/11941140/18785312/f8bfb234-81b0-11e6-95ab-7f3bf3731f28.png)

Thanks

**Comment by Ruud-cb** [comment] 2016-09-27 09:02
I had the same problem. Plunker is not correct there anymore but you might have done the same thing. #1041

**Comment by SharpieX** [comment] 2016-10-06 12:41
+1  Same thing happening for me after updating columnDefs and payload all columns are not visible 
i tried to use  this but didnt work for me 

setTimeout(function () {
   $scope.gridOptions.api.refreshView();
 }, 100)

**Comment by SharpieX** [comment] 2016-10-08 04:53
@Ruud-cb try using suppressColumnVirtualisation:true in gridOptions

**Comment by Ruud-cb** [comment] 2016-10-08 13:57
@SharpieX I already solved it there by not setting the `colId` variable.

**Comment by ceolter** [comment] 2016-10-12 10:11
not sure if still relevant, but try this if not already:
"colId should be strings, not numbers. update your plunker to use strings and it works perfect"

also, can you verify, this is failing in latest 6.2.x? another customer had this issue and i fixed it. cant' remember what was the problem, but it's fixed.

another thing you can try is suppress column virtualisation (suppressColumnVirtualisation=true). it may be the grid isn't able to work out the width of the grid and is only rendering the first column. if this does fix it, then it is something to do with your framework that is stopping the grid from finding out it's true width. putting a grid refresh into a timeout may also fix this.

**Comment by AbuSufyan** [comment] 2016-10-21 15:56
Yes we used v6.2, visibility issue is fixed by using suppress column virtualization, but we face following issues with Pinned columns 

1. Row hover style is not working on pinned column. It's only worked on the non-pinned columns.
2. When we move vertical scrollbar full down (red encircled) and horizontal scrollbar full right and selects any row and switching between tabs, then vertical scrollbar moves up and horizontal scrollbar moves left, and our row selection is disturbed.
3. In the snapshot, the first column is pinned. You can see row hover style is not worked on pinned column.
![10-21-2016 8-31-31 pm](https://cloud.githubusercontent.com/assets/11941140/19604235/d5dd15c6-97cd-11e6-8d56-2962bdf6eafa.png)

4. After tab switching, scrollbars didn't maintain state and goes on default position.
![10-21-2016 8-42-05 pm](https://cloud.githubusercontent.com/assets/11941140/19604497/fe9be608-97ce-11e6-9835-9f710a240297.png)
5. It's happening in following range of Internet Explorer versions 
![10-20-2016 9-29-56 pm](https://cloud.githubusercontent.com/assets/11941140/19604758/0e81ace6-97d0-11e6-9a35-3eebfbec3d0d.png)
![10-20-2016 9-25-50 pm](https://cloud.githubusercontent.com/assets/11941140/19604829/635fb5f0-97d0-11e6-95f7-ae57323b6090.png)

How do we fix above issues?
Any help would be appreciated.

Thanks in advance

**Comment by ceolter** [comment] 2016-10-28 14:41
the problem is happening because the grid for some reason does not know how wide it is, so it is not rendering all the columns correctly.

if you resize your browser, this should fix the problem (not saying it's a fix, just saying that when the grid finds our it's real size, then this issue goes away).

is it only IE? can you recreate in a plunker?

**Comment by ceolter** [comment] 2017-01-19 17:31
i believe this issues is fixed in the latest. if not, please advise and i'll reopen.

**Closed by ceolter** 2017-01-19 17:31 UTC

**Comment by aprapplicationsupport** [comment] 2017-07-12 20:13
Sorry to bump this old thread, but I'm seeing the same issue in 10.1.0. I've attached a gif to show the behavior. Any updates on this by chance?
![bootstrap tab bug](https://user-images.githubusercontent.com/28930982/28137925-f8133548-671c-11e7-931d-0083a254fd44.gif)

**Comment by VaishaliJain09** [comment] 2017-09-26 11:56
I am also facing this issue.  Grid does not render all the columns. But when it is resized, I can see all columns. Did anyone find the resolution of this problem?
Chrome version - 61.0.3163.100
ag-grid version - 11
I am using ag-grid-react.

Thanks in advance!

**Comment by SharpieX** [comment] 2017-09-26 13:42
@VaishaliJain09 did you tried this  suppressColumnVirtualisation:true ?

**Comment by VaishaliJain09** [comment] 2017-09-27 05:08
Yes, I know the issue gets resolved using this property. But setting this property true makes grid too slow in IE. Therefore I do not want to use it. Is this the only solution?

**Comment by gabriele-fanchini** [comment] 2017-11-17 11:33
I have the same issue on Chrome 62:

"ag-grid": "14.1.0",
"ag-grid-angular": "14.1.0"

setting the "suppressColumnVirtualisation:true" work around make the grid very slow, especially on tablet...

**Comment by prabhat112** [comment] 2018-04-24 21:01
We are also facing this issue. This is due to the unpinned columns. The headers are not aligning with the data after 'suppressColumnVirtualisation:true'.

**Comment by tncho** [comment] 2018-06-08 02:14
Not sure if it's still relevant as of today, but I've encountered this issue recently as well and 
 invoking the doLayout() method on gridOptions after visible column changes seem to have solved it, like:

`onGridColumnsChanged: (params) => 
params.api.doLayout()
`

**Comment by mravenash** [comment] 2018-06-22 01:21
I am still having this issue. Neither doLayout() or suppressColumnVirtualisation:true fixed my issue. Are there any other recommendations?

**Comment by aprapplicationsupport** [comment] 2018-09-11 19:44
I just found a terrible hack that gets around this bug.. I just find a column that I know is going to be there, and I have to autosize at least one column for this to work :/

// Grid will only render the first column if we don't do this
// If we do it once, the first column is always small
// If we do it twice, the autosize column actually goes through
setTimeout(() => {
     this.gridOptions.columnApi.autoSizeColumns(["ColumnName"]);
     setTimeout(() => {
          this.gridOptions.columnApi.autoSizeColumns(["ColumnName"]);
      });
});`

**Comment by dduraipandian91** [comment] 2018-11-02 14:32
I was facing the same problem even after setting suppressColumnVirtualisation:true in the gridOptions. 
No solution worked for me. logging params in console, i figured that i can set from template tag in html as well.

I set something like this. It worked well for me. 

[enableColResize]="true"
**[suppressColumnVirtualisation] ="true"**

I am using below version. Hope this helps someone.

 "ag-grid-angular": "^19.1.1",
 "ag-grid-community": "^19.1.1",

**Comment by zds-d** [comment] 2019-08-24 12:15
"@angular/core": "~8.0.3",
    "ag-grid-angular": "^21.1.0",
    "ag-grid-community": "^21.1.1",
    "ag-grid-enterprise": "^21.1.1",

I used angular  router  + snapshot + aggrid and I also have this problem.  This problem can be solved by using suppressColumnVirtualisation:true.  But our form has no paging, there are tens of thousands of data, so we can't use it.

I used this method to solve： 

` constructor(private router: Router,
    private activatedRoute: ActivatedRoute) {

    this.router.events.subscribe((event) => {

      if (event instanceof NavigationStart && event.url == '/t1') {
        this.ag1._nativeElement.querySelector('.ag-header-viewport .ag-header-container').style.transform = 'translateX(0px)';
      }
    })

  }`
