### ISSUE TITLE
[filtering] Tree filter only the last chilren effective

### ISSUE THREAD

**Issue by ohohco** [ceolter/ag-grid#188] opened 2015-06-06 06:01 UTC

**Comment by ceolter** [comment] 2015-06-06 09:04
yes the filter only filters leaf nodes. that's the current design. i'm not sure if your raising this as a bug, a feature request, or just asking a question!!! if just a question, please use the board, as issues should be 'work to be done' for me. thanks :)

**Comment by ohohco** [comment] 2015-06-07 01:45
I hope I can search all nodes,not just last children with `quickFilterText`

**Comment by ohohco** [comment] 2015-06-08 08:34
I means that, if the grid is tree like `fileBrowser`, i want search the data , i can just search the last child,if the node is group=true  ,how to get it with filter

**Comment by ceolter** [comment] 2015-06-08 10:41
linked to https://github.com/ceolter/angular-grid/issues/110

**Comment by openseah** [comment] 2016-05-06 06:18
@ceolter  Any update for this feature request?

**Comment by ceolter** [comment] 2016-05-10 07:51
nope.

**Comment by jeffshaver** [comment] 2016-07-21 15:59
@ceolter my team needs this as well. we are using the quick filter and our header rows aren't empty, so it would be useful to be able to search for things within the header row.

**Comment by Haemoglobin** [comment] 2016-08-10 17:21
:+1:  It's possible to implement this yourself with a custom filter and then in the doesFilterPass callback you can return true if the filter text matches this node or any of this node's parents. It helps in this case to have a reference to the parent in your own model as I'm not sure that the ag-grid node object does. This might only work if you do your own grouping (as in Tree Data) rather then the grid grouping itself.

https://www.ag-grid.com/angular-grid-filtering/index.php

**Comment by ceolter** [comment] 2016-08-16 10:44
grid node does have reference to parent

**Comment by Pothanna** [comment] 2016-09-06 13:27
How to call the ag-grid methods in aurelia framework? I'm using setQuickFilter() in aurelia framework but it's showing setQuickFilter() is undefined. 
can any one help with this issue?

**Comment by ceolter** [comment] 2017-01-23 12:36
closing this as it is a duplicate of https://github.com/ceolter/ag-grid/issues/110

**Closed by ceolter** 2017-01-23 12:36 UTC
Labels: enhancement
